- shark/iree_utils.py
- shark/shark_runner.py
- shark/torch_mlir_utils.py
Currently supports export of torch-mlir module (as /tmp/[modulename]>.mlir) and iree bytecode module (/tmp/[<modulename].vmfb) via the --save_mlir and --save_vmfb command line flags.
Need to verify that exported modules run correctly through IREE CLI tools before merging.
> Add shark-runner command line options for saving modules.

- README.md
- shark/examples/minilm_jit.py
- shark/parser.py
- shark/shark_runner.py
Centralized the shark_args parser. Also added the --device flag that
specifies the device on which the inference or training is to be done.
> Centralize the parser location. Also add the --device flag.

- shark/iree_utils.py
- shark/shark_runner.py
- shark/torch_mlir_utils.py
`run_on_refbackend` is added to run linalg_on_tensors_backend compiled
code on torch-mlir's refbackend. Also, added gpu configs and flags.
> Add `run_on_refbackend` for torch-compiled modules.

- shark/examples/eager_mode.py
- shark/iree_eager_backend.py
- shark/iree_utils.py
- shark/shark_runner.py
Eager mode hidden behind `SharkMode` (see `shark/examples/eager_mode.py`).
```
TorchMLIRTensor([[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], backend=EagerModeRefBackend)
TorchMLIRTensor([[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], …
```
> TorchMLIR eager mode with IREE backend

- inference/README.md
- inference/src/dshark.cc
Updated the inference README.
Confirmed dshark backend can be run with Triton's perf_analyzer.
Also made small changes to the source file, mostly cleaning up code and removing log statements.
> Updated the inference README

- shark/examples/minilm_benchmark.py
- shark/iree_utils.py
- shark/shark_inference.py
- shark/shark_runner.py
-Introduce SharkBenchmark that bench models on regular torch, shark-py, and shark-c.
-Integrate iree-benchmark-module into Shark.
-Refactor SharkRunner to have low level API control.
> Add Shark Benchmark

- shark/examples/shark_inference/minilm_jit.py
- shark/iree_utils.py
-Add correct vulkan flag to run minilm_jit
-Add automatic specification of target triple for better speed.
-Will work when https://github.com/nod-ai/SHARK-Runtime/releases/tag/candidate-20220601.20 gets
released, for now we can replace the shark release link to this on setup_venv.sh to work.
> Rectify Vulkan Flags and Command to obtain Vulkan Target Triple

- shark/iree_utils.py
- shark/shark_runner.py
- shark/tests/test_benchmark.py
1. Refactored get_iree_module to a function that convert mlir->vmfb. (helps with generation of correct vmfb for benchmarking)
2. Added benchmarking test
3. minor cleanups and fix
Example:
```bash
python -m shark.examples.shark_inference.minilm_benchmark --device="cpu"
```
> Refactor get_iree_module to work with SharkBenchmark

- .gitignore
- shark/examples/shark_training/bert_training_load_tf.py
- shark/examples/shark_training/bert_training_tf.py
- shark/iree_utils.py
- shark/parser.py
- shark/shark_runner.py
- shark/shark_trainer.py
- shark/torch_mlir_utils.py
Added:
-Generalized save_mlir for tensorflow+torch
-Return loss for tf train since that's what we need to observer training 
-Remove return of self.trainable_params isn't updated in the mlir runs.
To try load and save:
```bash
python -m shark.examples.shark_training.bert_training_load_tf --device="cpu" --save_mlir
python -m shark.examples.shark_training.bert_training_load_tf --device="cpu"
python -m shark.examples.shark_training.bert_training_load_tf --device="cpu" --download_mlir_path=/tmp/tf_bert.mlir
```
Should work on device of your choice(cpu/gpu/vulkan).
> Add saving and loading of mlir to run.

- .github/workflows/test-models.yml
- .gitignore
- benchmarks/hf_model_benchmark.py
- benchmarks/hf_transformer.py
- requirements-importer.txt
- requirements.txt
- setup_venv.sh
- shark/iree_utils.py
- shark/shark_runner.py
- shark/tests/test_hf_benchmark.py
-Add HF Benchmarker class.
-Add sample to benchmark HF model.
Example:
```bash
python -m benchmarks.hf_model_benchmark --num_iterations=10 --model_name="microsoft/MiniLM-L12-H384-uncased"
```
> ORT-HF Benchmark Integration

- tank/conftest.py
- tank/pytorch/albert_test.py
- tank/pytorch/alexnet_test.py
- tank/pytorch/bert_test.py
- tank/pytorch/minilm_test.py
- tank/pytorch/resnet101_test.py
- tank/pytorch/resnet18_test.py
- tank/pytorch/resnet50_test.py
- tank/pytorch/squeezenet_test.py
- tank/pytorch/wide_resnet50_test.py
Save MLIR input for individual test cases by passing `--save-mlir` option through pytest. Can set `IREE_SAVE_TEMPS=<dir>` env variable to specify directory to which MLIR input will be exported.
Example:
Running from base SHARK directory,
`IREE_SAVE_TEMPS=iree_temps_bert_dynamic  pytest --save_mlir tank/pytorch/bert_test.py::BertModuleTest::test_module_dynamic_cpu`
will save the input MLIR to `SHARK/iree_temps_bert_dynamic/core-input.mlir`.
If a directory is not specified, the MLIR input will be saved to `/tmp/model.mlir` by default.
Note: currently, names for saved MLIR input files are not unique, so it is not advised to use the --save_mlir option with pytest when running more than one test case at a time.
> Enable passing of --save-mlir cmd-line option through pytest.

- tank/tf/conftest.py
- tank/tf/hf_masked_lm/albert-base-v2_test.py
- tank/tf/hf_masked_lm/bert-base-uncased_test.py
- tank/tf/hf_masked_lm/camembert-base_test.py
- tank/tf/hf_masked_lm/convbert-base-turkish-cased_test.py
- tank/tf/hf_masked_lm/deberta-base_test.py
- tank/tf/hf_masked_lm/distilbert-base-uncased_test.py
- tank/tf/hf_masked_lm/electra-small-discriminator_test.py
- tank/tf/hf_masked_lm/funnel-transformer_test.py
- tank/tf/hf_masked_lm/layoutlm-base-uncased_test.py
- tank/tf/hf_masked_lm/longformer-base-4096_test.py
- tank/tf/hf_masked_lm/mobilebert-uncased_test.py
- tank/tf/hf_masked_lm/mpnet-base_test.py
- tank/tf/hf_masked_lm/rembert_test.py
- tank/tf/hf_masked_lm/roberta-base_test.py
- tank/tf/hf_masked_lm/tapas-base_test.py
- tank/tf/hf_masked_lm/tiny-random-flaubert_test.py
- tank/tf/hf_masked_lm/xlm-roberta-base_test.py
also adds/removes some pytest marks to TF tests
Adds pytest option to use IREE's TempFileSaver to generate reproduction artifacts during a test run.
Example usage and results:
> Add TempFileSaver pytest option to tank TF tests.

- shark/iree_utils.py
- shark/shark_inference.py
- shark/shark_runner.py
- tank/conftest.py
- tank/pytorch/conftest.py
- tank/tf/conftest.py
- tank/tf/hf_masked_lm/albert-base-v2_test.py
- tank/tf/hf_masked_lm/bert-base-uncased_test.py
- tank/tf/hf_masked_lm/camembert-base_test.py
- tank/tf/hf_masked_lm/convbert-base-turkish-cased_test.py
- tank/tf/hf_masked_lm/deberta-base_test.py
- tank/tf/hf_masked_lm/distilbert-base-uncased_test.py
- tank/tf/hf_masked_lm/electra-small-discriminator_test.py
- tank/tf/hf_masked_lm/funnel-transformer_test.py
- tank/tf/hf_masked_lm/layoutlm-base-uncased_test.py
- tank/tf/hf_masked_lm/longformer-base-4096_test.py
- tank/tf/hf_masked_lm/mobilebert-uncased_test.py
- tank/tf/hf_masked_lm/mpnet-base_test.py
- tank/tf/hf_masked_lm/rembert_test.py
- tank/tf/hf_masked_lm/roberta-base_test.py
- tank/tf/hf_masked_lm/tapas-base_test.py
- tank/tf/hf_masked_lm/tiny-random-flaubert_test.py
- tank/tf/hf_masked_lm/xlm-roberta-base_test.py
- tank/tflite/conftest.py
Use --benchmark flag with pytest to generate a bench_results.csv that contains results for inference benchmarks on frontend, SHARK-python, and SHARK-iree-c for each test case in the pytest run.
This commit only adds benchmark functionality to TensorFlow tests. Support for other frontends will come in follow-up commits.
These TF tests should serve as a model for how tests should be structured in all frontends, BEFORE the importer/downloader split happens.
Example .csv obtained by running static cpu TF tests with the --benchmark option:
[bench_results.csv](https://github.com/nod-ai/SHARK/files/8953374/bench_results.2.csv)
> Equip TF tests with save_mlir, save_vmfb, and benchmark to .csv options.

- shark/shark_downloader.py
- tank/tflite/albert_lite_base/albert_lite_base_tflite_mlir_test.py
Change some path process. Now you can use  sharkdownloder to get mlir file for tf/torch/mhlo/tosa/jax
```
self.shark_downloader = SharkDownloader(model_name="Bert",
tank_url="https://storage.googleapis.com/shark_tank",
local_tank_dir="./../gen_shark_tank",
model_type="tensorflow")
tf_mlir_model = self.shark_downloader.get_mlir_file()
self.shark_downloader = SharkDownloader(model_name="MiniLM-L12-H384-uncased",
tank_url="https://storage.googleapis.com/shark_tank",
local_tank_dir="./../gen_shark_tank",
model_type="torch")
torch_mlir_model = self.shark_downloader.get_mlir_file()
```
Then use these mlir model as SharkInference model input.
> Add tf/torch/mhlo/tosa/jax support for SharkDownloader

- shark/parser.py
- tank/tf/hf_masked_lm/albert-base-v2_test.py
- tank/tf/hf_masked_lm/bert-base-uncased_test.py
- tank/tf/hf_masked_lm/camembert-base_test.py
- tank/tf/hf_masked_lm/convbert-base-turkish-cased_test.py
- tank/tf/hf_masked_lm/deberta-base_test.py
- tank/tf/hf_masked_lm/distilbert-base-uncased_test.py
- tank/tf/hf_masked_lm/electra-small-discriminator_test.py
- tank/tf/hf_masked_lm/funnel-transformer_test.py
- tank/tf/hf_masked_lm/layoutlm-base-uncased_test.py
- tank/tf/hf_masked_lm/longformer-base-4096_test.py
- tank/tf/hf_masked_lm/mobilebert-uncased_test.py
- tank/tf/hf_masked_lm/mpnet-base_test.py
- tank/tf/hf_masked_lm/rembert_test.py
- tank/tf/hf_masked_lm/roberta-base_test.py
- tank/tf/hf_masked_lm/tapas-base_test.py
- tank/tf/hf_masked_lm/tiny-random-flaubert_test.py
- tank/tf/hf_masked_lm/xlm-roberta-base_test.py
Set TempFileSaver path directory to shark_args.repro_dir
Fixup xfails.
> Generate test-specific repro path for each TF model test.

- generate_sharktank.py
- shark/shark_importer.py
- tank/model_utils_tflite.py
- tank/tflite/albert_lite_base/albert_lite_base_tflite_test.py
Delete SharkImporter forward and compile. Make it return mlir_model so SharkInference can use it as the input model.
Rewrite the tflite SharkImporter test file: albert_lite_base_tflite_test.py
Quick reference on how to use it:
```
my_shark_importer = SharkImporter(
model_name="albert_lite_base",
model_type="tflite"
)
mlir_model = my_shark_importer.get_mlir_model()
inputs = my_shark_importer.get_inputs()
shark_module = SharkInference(
mlir_model,
inputs,
device=self.device,
dynamic=self.dynamic
)
shark_module.set_frontend("tflite-tosa")
shark_module.compile()
mlir_results = shark_module.forward(inputs)
```
> SharkImporter for tflite without forward and compile

- shark/torch_mlir_utils.py
This currently enables the upstream `torch_mlir.compile` API for static cases.
> Add the `torch_mlir.compile` API for static cases.

- shark/iree_utils/vulkan_utils.py
- tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_pytorch_test.py
- tank/pytorch/albert-base-v2/albert-base-v2_pytorch_test.py
- tank/pytorch/bert-base-uncased/bert-base-uncased_pytorch_test.py
- tank/pytorch/distilbert-base-uncased/distilbert-base-uncased_pytorch_test.py
- tank/pytorch/mobilebert-uncased/mobilebert-uncased_pytorch_test.py
- tank/pytorch/resnet101/resnet101_pytorch_test.py
- tank/pytorch/resnet18/resnet18_pytorch_test.py
- tank/pytorch/resnet50/resnet50_pytorch_test.py
- tank/pytorch/squeezenet1_0/squeezenet1_0_pytorch_test.py
- tank/pytorch/wide_resnet50_2/wide_resnet50_2_pytorch_test.py
Previously the device attribute was not passed and device was
hardcoded to "cpu". So every tests were running on cpu.
> Bug fix: Pass the device attribute appropriately.

- .github/workflows/test-models.yml
- tank/gpu_suite.sh
- tank/masked_lm_tf.py
- tank/model_utils_tf.py
- tank/tf/MiniLM-L12-H384-uncased_tf_test.py
- tank/tf/hf_masked_lm/albert-base-v2_tf_test.py
- tank/tf/hf_masked_lm/bert-base-uncased_tf_test.py
- tank/tf/hf_masked_lm/camembert-base_tf_test.py
- tank/tf/hf_masked_lm/convbert-base-turkish-cased_tf_test.py
- tank/tf/hf_masked_lm/deberta-base_tf_test.py
- tank/tf/hf_masked_lm/distilbert-base-uncased_tf_test.py
- tank/tf/hf_masked_lm/electra-small-discriminator_tf_test.py
- tank/tf/hf_masked_lm/funnel-transformer_tf_test.py
- tank/tf/hf_masked_lm/layoutlm-base-uncased_tf_test.py
- tank/tf/hf_masked_lm/longformer-base-4096_tf_test.py
- tank/tf/hf_masked_lm/mobilebert-uncased_tf_test.py
- tank/tf/hf_masked_lm/mpnet-base_tf_test.py
- tank/tf/hf_masked_lm/rembert_tf_test.py
- tank/tf/hf_masked_lm/roberta-base_tf_test.py
- tank/tf/hf_masked_lm/tapas-base_tf_test.py
- tank/tf/hf_masked_lm/tiny-random-flaubert_tf_test.py
- tank/tf/hf_masked_lm/xlm-roberta-base_tf_test.py
xfails will be updated once issues are filed for remaining failures.
> Force TensorFlow to use CPU when generating model and golden values.

- tank/pytorch/v_diffusion/v_diffusion.py
The PyTorch decomposition for the op `aten.upsample_bilinear2d.vec`
is merged in the upstream repo and hence removed from this file.
> Remove op decomposition from the v_diffusion.py

- tank/convbert-base-turkish-cased_tf/convbert-base-turkish-cased_tf_test.py
- tank/pytorch/alexnet/alexnet_test.py
- tank/pytorch/mobilebert-uncased/mobilebert-uncased_test.py
- tank/pytorch/squeezenet1_0/squeezenet1_0_test.py
Xfail Marked for:
1. ConvBertModuleTest::test_module_static_vulkan
2. AlexnetModuleTest::test_module_static_vulkan
3. MobileBertModuleTest::test_module_static_vulkan
4. SqueezenetModuleTest::test_module_dynamic_vulkan
> Mark XFail for M1 Vulkan Failures

- shark/iree_utils/gpu_utils.py
- shark/parser.py
This commit fixes numerics issues caused by TensorFloat32 execution on TensorFlow Masked LM models and PyTorch MobileBert.
TODO:
Re-enable the passing of this flag for when models require benchmarking -- this is a little sticky as we first validate, then use the same compiled .vmfb to benchmark on pytest runs.
Perhaps we can relax the tolerance when --benchmark is passed.
> Disable passing of sm_arch to iree-compile CL args by default.

- .github/workflows/test-models.yml
- shark/iree_utils/compile_utils.py
This fixes issues during compilation of the IREE module from a flatbuffer binary.
> Add config.VmModule argument to from_flatbuffer call.

- shark/parser.py
- shark/shark_benchmark_runner.py
- tank/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_test.py
- tank/MiniLM-L12-H384-uncased_torch/MiniLM-L12-H384-uncased_torch_test.py
- tank/model_utils.py
- tank/model_utils_tf.py
NOTE: benchmark reference numbers from TF on GPU are showing CPU results as GPUs are disabled in tf.config.
It's a bit tricky to navigate TF GPU execution/visibility so that will come in a follow-up.
> Add benchmarks to MHLO miniLM and resnet50 and fix some issues with tolerances for TF32.

- generate_sharktank.py
- shark/shark_importer.py
- tank/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_test.py
- tank/distilbert-base-uncased_tf/distilbert-base-uncased_tf_test.py
- tank/mpnet-base_tf/mpnet-base_tf_test.py
- tank/tf/tf_model_list.csv
Speeds up performance on TF miniLM ~2x for IREE-C
On A100 instance:
Old: 
```
microsoft/MiniLM-L12-H384-uncased,shark_python,False,mhlo,cpu,15.995373652533207,62.51807689666748,100,2022-08-17 23:15:48.937674
microsoft/MiniLM-L12-H384-uncased,shark_iree_c,False,mhlo,cpu,19.047619047619047,52.5,100,2022-08-17 23:15:49.621349
```
New:
```
microsoft/MiniLM-L12-H384-uncased,shark_python,False,mhlo,cpu,37.91355342029316,26.375792026519775,100,2022-08-17 23:11:33.097457
microsoft/MiniLM-L12-H384-uncased,shark_iree_c,False,mhlo,cpu,43.290043290043286,23.1,100,2022-08-17 23:11:34.094265
```
> Fix sourcing for canonical MiniLM shark_tank model artifacts.

- shark/shark_benchmark_runner.py
- tank/pytorch/bench_results.csv
- tank/pytorch/torch_model_list.csv
- Rename "dynamic" bool field to "shape_type" and provide "static" or "dynamic" as values.
- Provide datatype in benchmark results.
- Computes and provides comparison with PyTorch (or Tensorflow) for shark-python and shark-iree-c benchmarks (e.g. 2x slower/faster)
- Adds tags and notes to tank/pytorch/torch_model_list.csv to be added to the first entry row (PT/TF benchmark) for every benchmarked test case.
Example:
```
model,engine,dialect,device,shape_type,data_type,iter/sec,ms/iter,vs. PyTorch/TF,iterations,param_count,tags,notes,datetime
microsoft/MiniLM-L12-H384-uncased,tensorflow,mhlo,cpu,static,int32,17.557325179243154,56.956284046173096,=,100,66M,"nlp,bert-variant,transformer-encoder","Large version has 12 layers, 384 hidden size,Smaller than BERTbase (66M params vs 109M …
```
> Add some metadata and features to benchmark results.

- .github/workflows/test-models.yml
- README.md
Also copies latest benchmarks to:
gs://shark-public/builder/bench_results/latest/bench_results_cpu_latest.csv
gs://shark-public/builder/bench_results/latest/bench_results_gpu_latest.csv
> Enable CPU benchmarks on test-models workflows.

- .github/workflows/test-models.yml
- conftest.py
- tank/test_models.py
Adds two pytest command-line options:
`--ci` -- designed for CI workflows, this option uploads reproducers to gs://shark-public/builder/repro_artifacts/ for any tests that fail during iree-compile or validation.
`--save_repro` -- saves all reproduction artifacts to SHARK/shark_tmp/saved/ whether or not the test succeeds.
> Add pytest options to save reproducers.

- .github/workflows/test-models.yml
- conftest.py
- tank/test_models.py
Also adds the --save_fails option to pytest suite for saving reproductions for failures locally.
> Include SHA in path to failure reproducers. Add --save_fails option.

- shark/torch_mlir_lockstep_tensor.py
Because aten._reshape_alias introduces strides, in many of the cases it shows up in eager mode it gives "incorrect" output. The solution is to force the Autograd/Torch-MLIR decomposition which is simply to treat it as a view op.
> [Lockstep] Hack to avoid aten._reshape_alias

- shark/model_annotation.py
Usage:
from shark.model_annotation import model_annotation
with create_context() as ctx:
module = model_annotation(ctx, input_contents=..., config_path=..., search_op=...)
Example:
The example is to annotate the minilm model with GPU config file. 
python model_annotation.py /nodclouddata/vivian/minilm_model/model.mlir /nodclouddata/vivian/minilm_model/model_config.json
> Update model annotation tool

- conftest.py
- shark/shark_downloader.py
- tank/test_models.py
Alternate shark tank URLs must have the same layout past the default URL's SHA (`custom_url/<modelname>/artifacts...`)
> Add pytest option to specify a URL for shark tank artifacts.

- .github/workflows/test-models.yml
- setup_venv.sh
torch-mlir requires a specific torch version to function correctly. The benchmark suite requires torch cuda.
> seperate importer and benchmark deps

- .github/workflows/test-models.yml
Allow one job per branch and kill previous jobs to prevent jobs from queuing up.
> Allow only one workflow job per branch

- README.md
- shark/examples/shark_inference/resnet50_script.py
- shark/iree_utils/benchmark_utils.py
- shark/iree_utils/compile_utils.py
- shark/parser.py
- shark/shark_inference.py
To produce benchmarks of individual dispatches, you can add --dispatch_benchmarks=All --dispatch_benchmarks_dir=<output_dir> to your command line argument.
> Added a dispatch benchmarking tool

- shark/examples/shark_inference/stable_diffusion/utils.py
- shark/iree_utils/_common.py
- shark/iree_utils/benchmark_utils.py
- shark/iree_utils/compile_utils.py
- shark/shark_importer.py
- tank/test_models.py
use --device flag to choose single vulkan device 
device name should be same as found in `./iree-run-module --list_devices=vulkan`
when choosing a specific device, ensure to provide appropriate `-iree-vulkan-target-triple`
> Add support for choosing vulkan device

- shark/iree_utils/compile_utils.py
In 749a2c2d iree_device_map and iree_target_map have been made functions but not all of the uses were updated.
> Fix dispatch saving code after 749a2c2d

- shark/shark_runner.py
Right now it would just terminate the process silently
> Actually print the error message when SharkRunner can't initialize the driver

- benchmarks/tests/test_benchmark.py
- shark/examples/shark_inference/CLIPModel_tf.py
- shark/examples/shark_inference/albert_maskfill_tf.py
- shark/examples/shark_inference/gpt2_tf.py
- shark/examples/shark_inference/minilm_benchmark_tf.py
- shark/examples/shark_inference/minilm_tf.py
- shark/examples/shark_inference/t5_tf.py
- shark/examples/shark_training/bert_training_tf.py
- tank/examples/MiniLM_tf/huggingface_MiniLM_gen.py
- tank/examples/MiniLM_tf/huggingface_MiniLM_run.py
- tank/examples/MiniLM_tf/seq_classification.py
- tank/examples/bert_fine_tuning/bert_fine_tune_tf.py
- tank/examples/bert_tf/bert_large_gen.py
- tank/examples/bert_tf/bert_large_run.py
- tank/examples/bert_tf/bert_large_tf.py
- tank/examples/bert_tf/bert_small_gen.py
- tank/examples/bert_tf/bert_small_run.py
- tank/examples/bert_tf/bert_small_tf_run.py
- tank/examples/bert_tf/seq_classification.py
- tank/model_utils_tf.py
In order to enable the XLA compiler, functions need to be explicitly annotated. Latencies are lower with XLA enabled: https://www.tensorflow.org/xla
> Enable XLA compiler for TF models

- shark/shark_benchmark_runner.py
- tank/model_utils_tf.py
- tank/test_models.py
TF visible devices was being hardcoded to use CPU. This PR fixes TF CPU/GPU paths so that GPU can be used when benchmarking CUDA. Each test much run in a separate process to get around TF global GPU memory management: https://github.com/tensorflow/tensorflow/issues/36465#issuecomment-582749350
> Use correct TF device depending on configuration

- shark/examples/shark_inference/stable_diffusion/main.py
- shark/iree_utils/compile_utils.py
The numpy copy causes a ~1s overhead for VAE on windows.
> Don't do a numpy copy on the results from compiled vm

- shark/examples/shark_inference/stable_diffusion/model_wrappers.py
Changes to download model from HF acc to precision
Takes half precision cuda path for fp16 and defaults to fp32 
No support for other precisions (int8) as of now.
> Enable f32 path for SD

- shark/iree_utils/vulkan_utils.py
To enable AMD gpus on macOS, we need this detection to let the compiler know that we would be needing moltenVK to use this GPU.
> [Vulkan][Utils] Automatic platform/OS detection

- shark/iree_utils/compile_utils.py
- shark/parser.py
- tank/model_utils.py
- tank/test_models.py
minor fixes:
- enable mobilenet on cpu
- fix deprecated torchvision api usage
adds support for model-specific automatic iree-compile flag assignment via shark_args assignments in pytest
adds `--iree-flow-enable-conv-nchw-to-nhwc-transform` flag by default.
> Enable conv nchw-to-nhwc flag by default for most models + minor fixes

- shark/examples/shark_inference/stable_diffusion/stable_args.py
- shark/examples/shark_inference/stable_diffusion/utils.py
By default the flag is enable only in Debug builds
This PR defaults the flag to false for Stable Diffusion Inference. 
Also, categorically rearranges args used for SD.
> add flag for toggling vulkan validation layers

- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/utils.py
- shark/iree_utils/_common.py
- shark/iree_utils/compile_utils.py
- shark/iree_utils/vulkan_utils.py
This PR adds support for automatically deducing target triple for specified vulkan devices (for systems with multiple cards too)
- Takes vulkan device name from iree_driver's query_available_devices instead of vulkaninfo
- Give framework to add support for other devices (API added to _common)
> Get appropriate target triple for specified Vulkan device

- shark/iree_utils/vulkan_utils.py
Just happened to have this card on my Windows machine and verified that the SD demo works on it.
```
Average step time: 144.26142692565918ms/it
Clip Inference Avg time (ms) = (205.001 + 44.000) / 2 = 124.501
VAE Inference time (ms): 281.001
Total image generation time: 7.856997728347778sec
```
I'd love to add an API upstream to derive compiler tuning flags from a host device.
> Add config stanza for NVIDIA RTX 2080.

- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/stable_args.py
Printing might incur extra time to runtime. Hence, we add a flag to hide it. To disable printing please set this flag `--hide_steps`.
> [SD][CL] Disable print at every iteration.

- shark/examples/shark_inference/stable_diffusion/opt_params.py
- web/models/stable_diffusion/cache_objects.py
- web/models/stable_diffusion/opt_params.py
1. SD web uses tuned models for rdna3 card irrespective of `--use_tuned` flag.
2. Current SD web performance:
```Average step time: 52.650580406188965ms/it
Clip Inference time (ms) = 68.021
VAE Inference time (ms): 212.207
Total image generation time: 3.130343198776245sec```
> [SD][web] Fix performance issues on shark scheduler

- shark/examples/shark_inference/stable_diffusion/stable_args.py
- web/models/stable_diffusion/stable_args.py
Also use this flag `--use_compiled_scheduler` by default
> [SD] Set model max length 64 as default

- shark/examples/shark_inference/stable_diffusion/README.md
- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/model_wrappers.py
- shark/examples/shark_inference/stable_diffusion/opt_params.py
- shark/examples/shark_inference/stable_diffusion/stable_args.py
This PR adds support for 2 new variants of SD, which can be chosen using the `variant` flag in cli as follows:
- `--variant=<anythingv3 / analogdiffusion>`
- `version` flag is not required as we are only supporting the default versions of SD variants.
- the models in the tank currently work with max prompt length 77
> Add Anything v3 and AnalogDiffusion variants of SD

- web/models/stable_diffusion/opt_params.py
Currently tuned models are only available for stablediffusion/fp16 and rdna3 cards.
> [SD][web] Tuned models only for stablediffusion/fp16 and rdna3 cards

- shark/examples/shark_inference/stable_diffusion/stable_args.py
- web/models/stable_diffusion/stable_args.py
Windows perform can boost from 2.67s/image to 2.4523s/image. While Linux stays the same.
> [SD] Change default VMA large heap block size for windows perf

- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/schedulers.py
- shark/examples/shark_inference/stable_diffusion/utils.py
- shark/iree_eager_backend.py
- shark/iree_utils/compile_utils.py
- shark/shark_benchmark_runner.py
- shark/shark_inference.py
- shark/shark_runner.py
- tank/test_models.py
- web/models/stable_diffusion/main.py
- web/models/stable_diffusion/schedulers.py
- web/models/stable_diffusion/utils.py
-- Prviously SharkInference was compiling and providing run APIs
for a harcoded function with function name "forward".
-- This commit makes the compiling functionality generic and now
any function being defined within the module can be run.
-- It also creates an API to fetch all the function names defined
within the compiled module.
> [SharkInference] Make SharkInference compile the entire module

- shark/shark_downloader.py
Some ISP's (like mine) reserves 1.1.1.1 for internal testing, meaning _internet_connected(); needlessly retries for a minute until it fails even though my connection is fine. Propose 8.8.8.8 instead as this is also publically available and not normally blocked by ISPs.
> Change address for connection test

- shark/shark_downloader.py
Reverts nod-ai/SHARK#785
8.8.8.8 requires ICMP.
> Revert "Change address for connection test"

- shark/iree_utils/cpu_utils.py
Uses python uname utility for target triple manufacturing for cpu.
Draft because: Needs correct variation of target triple for windows supported by IREE
> pythonize uname for cpu target triple in windows

- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/stable_args.py
- we can use flag `--runs` to specify the number of images to be generated in one execution.
- this will use all the same prompt and generate `runs` number of images by consecutively running SD with a random seed value for each run.
- if `--seed` is provided in cli it will only be used for the first image.
- all images will be saved in current working directory or path specified by `--output_dir`
> add single execution multi-run SD

- shark/examples/shark_inference/stable_diffusion/README.md
- shark/examples/shark_inference/stable_diffusion/utils.py
-- This commit introduces a fix for .vmfb naming to strip away any
non-alphanumeric characters from `custom_model` path.
-- It also updates the README.md to include the `custom_model` arg.
> [SD-CLI] Fix vmfb naming + update README.md for `custom_model`

- web/index.py
- web/shark_sd.spec
Fixes [issues-816](https://github.com/nod-ai/SHARK/issues/816)
Also fixes issue reported in discord - exe did not have demo.css included
gets demo.css file path relative from index.pv \_\_file\_\_ parent rather than current working dir
add demo.css to spec file datas so its included in root folder of pyinstaller exe
> fix: :bug: resolve css file path relative to __file__ & add demo.css to spec file for pyinstaller

- requirements-importer.txt
the package "torchtriton" was removed from pypi after it was discovered that it was utilized to initiate dependency confusion attack over PyTorch. PyTorch since replaced it with "pytorch-triton". 
you can read more about it here: https://medium.com/checkmarx-security/py-torch-a-leading-ml-framework-was-poisoned-with-malicious-dependency-e30f88242964
> fix: replace malicious and deleted package

- shark/examples/shark_inference/stable_diffusion/main.py
-- This commit reorders loading of opt_params when `import_mlir` is not used.
> [SD-CLI] Reorder loading of opt_params when needed

- shark/examples/shark_inference/stable_diffusion/main.py
Doesn't regress the main.py script but system already pre-loaded the DLL so needs more testing.
> potential fix to pre-load DLL dir for torch-mlir

- shark/examples/shark_inference/stable_diffusion/README.md
- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/stable_args.py
-- This commit adds `batch_size` command-line arg.
-- It also involves replicating the prompt `batch_size` no. of times.
NOTE:
1. If user specifies just `1` prompt along with `batch_size`, then we'll be using the same prompt for inferring.
2. Else if user provides `>1` prompt then we'd need the number of prompts to be `=batch_size`. This gives the user a space to introduce different prompts and see them all getting inferred.
3. `batch_size` has been restricted to stay between `[1, 3]` because beyond that it is currently generating garbage output.
4. So, we'd require `runs` flag in case user wants to generate some arbitrary number of images (`>3`).
> [SD-CLI] Add `batch_size` command-line arg + prompt processing

- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/model_wrappers.py
- shark/examples/shark_inference/stable_diffusion/sd_annotation.py
- shark/examples/shark_inference/stable_diffusion/stable_args.py
- shark/examples/shark_inference/stable_diffusion/utils.py
- shark/model_annotation.py
- shark/shark_importer.py
- shark/torch_mlir_utils.py
Annotation on fly function only works when this PR merged upstream https://github.com/llvm/torch-mlir/pull/1797.
Before this patch merged, we'll need to make sure `--no-use_tuned` is passed when `--import_mlir` is used. The default of `--import_mlir` is set as `False` for now.
> Add SD model annotation on fly

- .github/workflows/test-models.yml
- requirements.txt
- tank/all_models.csv
- tank/test_models.py
This adds pytest-forked to requirements.txt -- to use this plugin, simply add `--forked` to your pytest command.
This way, each individual test case is run in its own subprocess, and error handling is seamlessly piped from the subprocess to pytest's reports.
@mariecwhite this should unblock us on the TF GPU enablement.
> Adds pytest-forked dependency to fix pytest memory accumulation issues.

- shark/examples/shark_inference/stable_diffusion/stable_diffusion_amd.md
The latest driver lists support for MLIR/IREE, which I imagine would be preferable to a special driver based on a pre-7900 series one, the warning about latest drivers lacking fixes notwithstanding.
I also copy-edited a few things in the Amd.md doc, and tweaked some wording; I'm also experiencing the mouse accuracy pointer issue with a default-sized cursor and UI.
> Mention latest RDNA3 driver support

- .github/workflows/test-models.yml
- build_tools/image_comparison.py
- build_tools/stable_diff_main_test.sh
- build_tools/stable_diffusion_testing.py
Currently disabled for CUDA because it only produces black images on my vm and on builder. 
Adds support for any model listed in model_config.json. However, any additions to model_config.json will need to be added to the golden images in order to work correctly. Alternatively I can change this to fail the builder if a new golden value isn't added.
Stable diff v1 also appears to be broken on ToM
Any failures in image comparison will be automatically uploaded to gs://shark_tank/testdata/builder
Note that any file 842b is a black image.  (failure)
> adding more robust main.py testing

- shark/examples/shark_inference/stable_diffusion/README.md
- shark/examples/shark_inference/stable_diffusion/main.py
- shark/examples/shark_inference/stable_diffusion/utils.py
-- This commit uses `load_pipeline_from_original_stable_diffusion_ckpt`
as exposed due to [Diffusers PR](https://github.com/huggingface/diffusers/pull/2019).
-- It also adds a support for the end users to use `.safetensors` along
with `.ckpt` file.
> [SD-CLI] Add support for .safetensors + Use diffusers pipeline to load SD

- shark/examples/shark_inference/stable_diffusion/stable_args.py
-- This commit renames SD negative_prompts flag.
NOTE: Any unique prefix of a flag is a valid flag. So, if we have `prompts` then we can use any of the following :-
1. `--pro`
2. `--prom`
3. `--promp`
4. `--prompt`
5. `--prompts`
> [NFC] Rename SD negative_prompts flag

- generate_sharktank.py
The upload option should be removed, as only the nightly builds should be uploading to gs://shark_tank/
> Remove --upload option from generate_sharktank.py

- shark/shark_benchmark_runner.py
- tank/all_models.csv
Torch Inductor currently fails with a CUDA error all torchvision models and some bert models.
> disable Torch Inductor autotuner in benchmarks

- apps/stable_diffusion/src/models/opt_params.py
- apps/stable_diffusion/src/utils/resources/model_db.json
we only have models in models_db for 2_1_base. now that diffusers is fixed we can actually generate 2_1 itself, but until we add support for that in the tank we should fetch 2_1_base for no-import_mlir
> Map 2_1 to 2_1_base

- apps/stable_diffusion/src/utils/utils.py
Looks like tuning on A100 doesn't necessarily translate to 40xx.
> Disable tuned models for sm_89

- apps/stable_diffusion/web/css/sd_dark_theme.css
This PR address issue https://github.com/nod-ai/SHARK/issues/582
Sadly, I haven't found a simple way to pass a theme as argument during Gradio init, to my knowledge this isn't supported.
Digging into their theming  system, when using http://localhost:8080/?__theme=dark , I realised they simply surcharges :root with a .dark class to apply the selected theme.
Using our custom sd_dark_theme.css, I copied all their .dark content to :root, as a result this makes the default Gradio white theme behave exactly the same way as the dark one.
I have also sanitized sd_dark_theme.css to replace all hardcoded colors by appropriate color vars:
Theme customisations should now only be needed by modifying vars declared in :root
I have tested this by commenting all :root rules, and indeed, minus the white …
> Make the dark theme default while launching web server

- .gitignore
the models folder will be stashed along with other changes and most likely kill git doing so.
> Update .gitignore to exclude models

- .github/workflows/nightly.yml
- generate_sharktank.py
Removes some arguments from generate_sharktank.py that were unusable after the stable_args import
Also changes nightly generated shark_tank to be copied to `gs://shark_tank/nightly` instead of `gs://shark_tank/latest`
Changes to `gs://shark_tank/latest` should be done either manually (when we need to update shark_tank for all users) or via a workflow job exclusive to this purpose.
> Remove non-SD args from generate_sharktank.py

- .github/workflows/test-models.yml
- apps/stable_diffusion/src/utils/utils.py
- generate_sharktank.py
- shark/shark_downloader.py
On import of the shark downloader, the shark_tank local cache (`WORKDIR` in shark_downloader.py) should be determined by the following method.
1. If shark_args.local_tank_cache is set, `WORKDIR` is set to that path.
2. If shark_args.local_tank_cache is not specified and there exists a locally generated shark_tank (at SHARK/gen_shark_tank), use that directory as `WORKDIR`. This is mostly for the nightly CI.
3. If conditions for 1 and 2 are not met, use `<HOME>/.local/shark_tank/` as `WORKDIR`.
Option #2's condition was written as an `if` statement instead of `elif` which caused option #3 to overwrite WORKDIR.
Ideally we don't use shark_args at all, but that is a larger undertaking.
> Fix local_tank_cache handling in shark_downloader.

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
Reverts nod-ai/SHARK#978. It will force --import_mlir to use untuned models until we have a fix on windows
> Revert "Delete unnecessary arg setting"

- .github/workflows/nightly.yml
- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/utils/stable_args.py
- process_skipfiles.py
This PR contains 2 commits :-
**Commit 1**
-- This commit adds a script to comment out the modules causing
AttributeError in exe.
-- It also adds the invocation of the script in the nightly build
both prior to and after invoking PyInstaller to create exe.
1. The first invocation comments the spurious modules.
2. The second invocation uncomments the same.
**Commit 2**
-- This commit gets done with the `--enable_stack_trace` flag from SD's execution.
> Fix `__file__ AttributeError` + Remove `--enable_stack_trace`

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/txt2img.py
- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/stable_args.py
disables usage of low_cpu_mem_usage=True in from_pretrained() calls. Can be re-enabled by using flag --low_cpu_mem_usage defaults to False to avoid spam as we don't include accelerate in our requirements.txt
> remove annoying accelerate warning

- shark/shark_benchmark_runner.py
Updates call to enable Torch Inductor.
To get Torch Inductor working, first update the version of Torch being run:
```
pip install numpy --pre torch[dynamo] --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117
```
This may cause dependency conflicts with `torch-mlir` so Torch imports may break.
Then uncomment the line:
```
#frontend_model = torch.compile(frontend_model, mode="max-autotune", backend="inductor")
```
in shark/shark_benchmark_runner.py
> Fix call to Torch Inductor

- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/resources/base_model.json
- apps/stable_diffusion/src/utils/stencils/stencil_utils.py
- adds functionality  for using stencil controlled image generation in the img2img pipeline
- currently supported stencils = canny edge detection
using stencils:
- specify input image for stencil creation and use `--img_path=`
- `--use_stencil=canny ` 
- prompt to get desired change on the stencil
- scheduler supported : DDIM
```
python apps/stable_diffusion/scripts/img2img.py --prompt=<prompt text>  --import_mlir --no-load_vmfb --enable_stack_trace --no-use_tuned --hf_model_id="runwayml/stable-diffusion-v1-5" --scheduler="DDIM" --use_stencil=canny --img_path=<path to input image>
```
> Add Stencil controlled SD in img2img pipeline

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
* Fix a gallery navigation bug introduced in Gradio V3.19:
Gallery navigation (thumbnail bar, preview) is not responding when the progress bar is active and the gallery is generating images (batch count >1). This problem was introduced by Gradio V3.19.
* Remove the full_width parameter used in Image.style as this is not supported by Gradio.
```
J:\sd\SHARK\shark.venv\Lib\site-packages\gradio\components.py:148: UserWarning: Unknown style parameter: full_width
warnings.warn(f"Unknown style parameter: {key}")
```
> [WebUi] Reactivate gallery nav, Remove full_width for Image.style

- setup_venv.sh
The latest version of IREE being installed in SHARK is 20230221.437 (see [summary.html](https://storage.googleapis.com/shark-benchmark-artifacts/latest/summary.html)). Update `setup_venv.sh` to also install pre-releases.
> Install IREE pre-releases

- apps/stable_diffusion/src/utils/utils.py
Testing the png metadata import using images from civitai.com, one image reported me this error:
```
File "D:\Stable_Diffusion\SHARK\apps\stable_diffusion\scripts\txt2img.py", line 162, in txt2img_inf
save_output_img(out_imgs[0], img_seed)
File "D:\Stable_Diffusion\SHARK\apps\stable_diffusion\src\utils\utils.py", line 608, in save_output_img
dictwriter_obj.writerow(new_entry)
File "C:\Users\m68k\AppData\Local\Programs\Python\Python311\Lib\csv.py", line 154, in writerow
return self.writer.writerow(self._dict_to_list(rowdict))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\m68k\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0] …
```
> Use utf-8 format for imgs_details.csv

- .flake8
- .github/workflows/test-models.yml
- .style.yapf
- pyproject.toml
This helps development where you can be sure that running locally
black .
flake8 .
will do the same as in the github job.
> Move linting opts from github workflow to config files

- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/stencils/stencil_utils.py
-- This commit removes the hardcoded HF ID for Stencil and instead
utilizes a dynamic instantiation of HF model.
> [SD] Use dynamic stencil HF repo id

- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/utils.py
- apps/stable_diffusion/web/utils/png_metadata.py
Load and apply png metadata using an Image field in the txt2img tab
As long as the source PNG was generated by Shark, it should be ok for all fields (local ckpt/safetensors, predefined models like AnythingV3 or hf model ids are supported)
Drag&dropping images from civitai also worked, but minor fixes need to be done to the png info itself, I will focus on that later.
To avoid a tedious review, it's also limited to the main feature itself for now:
* No fancy drag&drop in the prompt textfield. As far as I know, this is not supported natively by Gradio, a javascript hack is required. So it's just a simple image field for now.
* Only available in txt2img tab for now.
> [WebUi] txt2img_ui: Import png metadata

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/inpaint.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/scripts/txt2img.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/utils.py
- apps/stable_diffusion/web/utils/png_metadata.py
Hello, 
This should fix most of the Ui display problems introduced by Gradio 3.20
* Hide the download icon from the nod logo.
* Hide delete buttons visible in dropdowns.
* Hide selected icons visible next to dropdown entries.
* Display model names only (without fullpath) in model dropdowns.
* ckpt & safetensors names alphabetically sorted in model dropdowns.
* Renamed the "Strength" label in image-to-image tab by "Denoising Strength".
Note: For the download logo icon, I took the fast and lazy path, just hiding it. A safer option would have been to replace the image component by a html one. Perhaps for a later upgrade if a logo problem pop again.
Tested on all tabs, python version, windows binary distribution, and txt2img command line.
Have a nice week, and thanks a lot for this really …
> [Web] Improve dropdowns ux

- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
This is a small quality of life proposal:
The general use case when using the randomize seed button is a have a random behaviour on each generation.
Setting the seed to -1 avoid the necessity to click on the randomize button every time you want to generate a new batch.
> [Web] Randomize seed to -1

- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/utils/png_metadata.py
* Remove the custom model file extension from generated metadata. This adds compatibility with metadata generated by Auto1111.
* Better parsing from the WebUi "Import PNG info" box: Missing models are now reported in the console instead of the "hf model id " field. That was a pretty bad idea, and it should be less confusing for newcomers.
Note: It's now possible to drag&drop an image from civitai and import supported info.
> Fix png metadata

- shark/iree_utils/compile_utils.py
- shark/parser.py
Example:
$ python my_app.py --device_allocator caching debug
This will wrap the device allocator with first caching allocator then debug allocator.
$ python my_app.py --device_allocator caching
Only wrap with caching allocator.
> Add flag to augment the device allocator

- .gitignore
Ignore artifacts created by `pytest --benchmark tank/test_models.py`
> Add benchmark artifacts to .gitignore

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/inpaint.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
Add the stop button requested by the community:
Sadly, it's not possible to stop a running job in the current situation. 
Once the shark pipeline is called, there's is no feedback until a job is finished.
This button is effective for batch_count > 1 only, as a yield mechanism had been introduced for each image generation.
To avoid confusion for users, I decided to rename this button "clear queue" instead of "stop".
I also recommend to not spam the generate/clear buttons, it's very easy to run concurrent jobs.
I also noticed the code was not updated on the img2img, inpaint and outpaint tabs:
The yield for txt2img batch count was missing, this PR adresses that.
> [Web] Add a clear queue button

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- requirements.txt
Add support for Gradio v3.21.0:
* Remove Gradio pinned version in requirements.txt
* A type check was introduced by Gradio to insure input parameters are matching called functions: init_image was declared as Image but Gradio considers them as PIL, I simply removed the Image type (this was already the case for inpaint)
* Gradio dark theme was updated, this update was reported in our css.
> [Web] Upgrade Gradio to v3.21.0

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/inpaint.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/scripts/txt2img.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/utils.py
- apps/stable_diffusion/web/utils/global_obj.py
Using the global objects instead of creating one for each mode, so it won't create extra pipeline object when switching modes. Also clearing the cache when switching models to avoid memory leak.
> Clear memory cache when switching model and mode

- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
On display, the grouping had been lost on "Batch Count" & "Batch Size", this is a side effect of scaling the stop button relative to both batch sliders. 
I didn't bother editing the css to fix this cosmetic problem, as we will surely try to move back the button.
> [Web] Move "stop Batch" button to "Advanced Options" toggle

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/inpaint.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/scripts/txt2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/utils.py
- apps/stable_diffusion/web/utils/global_obj.py
"Stop batch" will now instantly cancel images generation for txt2img, img2img, inpaint and outpaint.
Sorry about the long PR, to avoid adding more, I have reported the implementation for the LoRA training and the upscaler tabs.
**Principle:** 
A pipeline status variable had been added with only two possible state for now (IDLE, CANCEL)
When the UI send a cancel signal, the pipeline stop iterating and return immediately.
The canceled image is skipped (not saved on disk and not displayed in the ui) as it is incomplete.
This is just an entry step, more work will be needed to finish a fully working "stop" feature.
If this is accepted, here is a list of possible updates I would like to add later:
* Implement Upscaler and LoRa training tabs.
* Manage more pipeline states: EXPORT_DIFFUSER, …
> [Web] Stop images

- shark/iree_utils/_common.py
- shark/iree_utils/benchmark_utils.py
- shark/iree_utils/compile_utils.py
- shark/iree_utils/vulkan_utils.py
- shark/shark_benchmark_runner.py
IREE is the only platform that supports peak memory reporting on both CPU and GPU. TensorFLow and PyTorch both report peak GPU memory usage.
> Add peak memory reporting for IREE, TF and PyTorch

- apps/stable_diffusion/scripts/txt2img.py
- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/models/opt_params.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/stable_args.py
Currently runs with `python apps/stable_diffusion/scripts/txt2img.py  --precision=fp16 --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd"  --use_quantize="int8" --max_length=77`.
> Add the int8 quantized model.

- apps/stable_diffusion/scripts/img2img.py
-- This commit updates Stencil resize feature to cap the size of
images within [128,768] as supported by the SD pipeline.
-- This solves the issue of scribble crashing on larger image.
> [SD] Fix Stencil scribble crash by updating image resize

- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/utils.py
-- This commit fixes custom model path for WebUI.
> [SD] Fix custom model path for WebUI

- shark/iree_utils/compile_utils.py
This should reduce the eval key spam on a crash.
> strip source map

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_inpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_upscaler.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
* Implements https://huggingface.co/AlanB/lpw_stable_diffusion_mod on all prompts. (Auto1111 emphasis syntax)
* Few modifications were needed from the original source: To ease the review I tagged them with #SHARK in the source code.
* No support for long prompts for now, as Shark runner is imposing a 77 chunck limit for embeddings.
* Very easy to rollback or switch to the old encoder if it's needed.
* Fully compatible with the old encoder: The new encoder produce exactly the same image as the old one if weights are all set to one.
Tested on txt2img, img2img, inpaint, outpaint and the txt2img command line script.
> [SD] Add weight emphasis to the prompts encoder

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_inpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_upscaler.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
Fix the error reported here: https://discord.com/channels/973663919757492264/1092903312740851843
Tested on prompthero/openjourney and confirmed:
pipe.tokenizer.model_max_length is returning 77 instead of 64, ending in a tensor shape error.
I suspect this tokenizer.model_max_length is always returning 77.
To fix the problem the real length was passed as an argument, and we're not relying on this tokeniser property anymore.
Wouldn't it be more appropriate to fix the property itself ?
I check the code and noticed than it is also used in the LoRA trainer.
> [SD] Fix encoder error for model_max_length not beeing 77

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/scripts/inpaint.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/scripts/upscaler.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/utils/global_obj.py
- Enable unloading clip on demand
- Workaround the memory leak of unloading models (It still keeps something in memory after unloading models and using gc would cause error. I think something is still referenced so it can't be cleaned. The workaround is creating the SD pipeline everytime if on demand.)
- Disable unloading models for outpainting becuase it would load and unload models for each direction
> Unload clip and workaround the memory leak for ondemand

- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/utils/png_metadata.py
Revert to Gradio return by list instead of dict, to remove txt2img ui dependencies from png_metadata.
https://gradio.app/blocks-and-event-listeners/#function-return-list-vs-dict
> [Web] remove txt2img ui dependencies from png_metadata

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
* Fix the Import PNG metadata box height (it's now controlled from the parent div)
* Add a default body background color.
* Gallery: Replace deprecated grid style option.
* Gallery: Add object_fit style property to get correct image ratio no matter the size.
> [Web] Style Fixes for Gradio V3.25.0

- apps/stable_diffusion/scripts/img2img.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- apps/stable_diffusion/web/ui/utils.py
- apps/stable_diffusion/web/utils/png_metadata.py
* Rename the two scheduler lists used by the Ui:  ~~scheduler_list_txt2img & scheduler_list~~ -> scheduler_list & scheduler_list_cpu_only.
* Scheduler Ui dropdowns defaulted to "EulerDiscrete" instead of "PNDM" as it's now fully supported everywhere.
It's working and generate correct images, but two minor problems were noticed:
* img2img: depending on the number of steps and the denoising strength, it can generate a noise image.
* outpaint: Expending more than one region will only output a partial image.
This is surely a side effect of this scheduler internally doubling the number of steps.
I have not removed it, as it's working in most situations.
> Update list of scheduler available for inferences

- apps/stable_diffusion/web/ui/img2img_ui.py
Currently when using the SD API, we print the entire input data dict which dumps the very long, non-human readable input image data.
Simplify the print statement such that prompt, negative prompt, and seed are printed exclusively.
> Don't dump image data on img2img api call.

- apps/stable_diffusion/src/schedulers/shark_eulerdiscrete.py
This changes the scheduler model names from something like  `euler_scale_model_input_1_512_512fp16` to `euler_scale_model_input_1_512_512_vulkan_fp16`
It is useful if you are going to use multiple backends (e.g cuda/vulkan) so that they dont try to use each others .vmfb
> Add device to scheduler model names

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
* Remove the "Saving images at" box located above sent buttons.
* Replace "Nothing to show" from the stableDiffusion text output by "Images will be saved at {path}".
* No more image scaling above 1.
**1440p and 4k users only:**
* Gallery is 768px height based.
* As long as images are under 768x768, they should all be displayed at the exact scale in main view mode.
* The full interface fit into screen (depends on the number of toggles opened in the left setting space), main app scrollbar is not triggered by the gallery anymore.
Sorry, if I didn't pushed further for small devices or 1080p users, but it simply don't fit right now.
I will certainly come back at it later to finetune more breakpoints.
> [Web] Gallery set to a 768px reference for high-end desktop users

- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- apps/stable_diffusion/web/ui/utils.py
* **models** or **args.ckpt_dir** (if args.ckpt_dir was provided)
* lora
* vae
* diffusers
* ckpt-dir was not provided: No change.
* ckpt-dir was provided: Skip root model folder check and creation, only recreate the sub folders structure inside ckpt-dir.
* Local inpainting models are filtered using the *-inpainting.(ckpt|safetensors) mask.
* Local upscaler models are filtered using the *-upscaler.(ckpt|safetensors) mask.
* They are now generated inside (models|args.ckpt_dir)/diffusers
* txt2img, img2img: stabilityai/stable-diffusion-2-1-base
* inpaint, outpaint: stabilityai/stable-diffusion-2-inpainting
* upscaler: stabilityai/stable-diffusion-x4-upscaler
> [Web] Models folders cleanup

- apps/stable_diffusion/shark_sd.spec
- apps/stable_diffusion/shark_sd_cli.spec
This PR fixes issues with pyinstaller missing `iree.compiler._mlir_libs` imports for registering dialects in the MLIR context during SHARK model_annotator (which imports the iree.compiler.ir context)
> Add iree hidden imports to SD spec

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/utils.py
- shark/shark_downloader.py
- tank_version.json
There is still work to do here -- the generation for SD models needs reviving and we need to get rid of the confusing "vulkan" addition to the SD sub-model directory/filenames. For now the existing artifacts are functional so we can re-enable these downloads to unblock those for whom the import_mlir path is not an option.
> Revive SD downloads from shark_tank.

- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/__init__.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- apps/stable_diffusion/web/utils/common_label_calc.py
- apps/stable_diffusion/web/utils/exif_metadata.py
_I realise that this is probably a bit much for a first contribution to a project, and may not fit with where you want the UI to go, but I needed it myself and was writing it anyway. Therefore PR upstream._  
My Chromebook is in the kitchen, my computer with the graphics card is not. So I run the webui on the computer, and use then browse in from the Chromebook. 
This has some problems, mostly due not having access to the filesystem on which the application is running.
* I can only see images for the last generation batch, rather than all the images I've made that are sitting under the output directory or where I've archived them.
* I can't look at the headers of existing .PNGs on the filesystem to see parameter info.
* I have some JPEG images where I have parameter info saved in the EXIF …
> Web/UI: Add an Output Gallery tab for SD

- shark/iree_utils/vulkan_target_env_utils.py
Adds **[VK_KHR_shader_integer_dot_product](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_integer_dot_product.html)** (a vulkan extension exposing the SPIR-V extension **[SPV_KHR_integer_dot_product](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_integer_dot_product.html)**) for some compatible Vulkan environments which is included in core Vulkan 1.3, it can have the potential to improve (most commonly) int8 inferencing/training speeds and better performance as dot products may be more optimal and most importantly accelerated on capable hardware.
This does likely require some changes to the backend to see any full use out of if possible, and I may have written this commit in an erroneous way …
> Add to and tweak vulkan configuration environments.

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_upscaler.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
Addresses issue https://github.com/nod-ai/SHARK/issues/1472
Changes:
* Hooks the cancel_sd function up to the Stop button on the upscaler tab.
* Adds checks for SD_STATE_CANCEL in the upscaler ui inference function.
* Sets and checks for SD_STATE_IDLE, SD_STATE_CANCEL in the upscaler pipeline in similar places to the non-upscaler pipeline (as in utils).
Known problems:
* If you press 'stop' on the upscaler tab, the next time you 'generate' on that tab it will be ignored, you need to press it again for the upscaler task to be triggered. No idea what is causing this.
> UI/Web: Fix upscaler stop button (mostly)

- apps/stable_diffusion/src/utils/utils.py
This is a temporary measure while we retune SD1.4 for rdna2. The current config fails during iree-compile.
> disable use_tuned on SD1.4 unet for rdna2

- apps/stable_diffusion/src/utils/sd_annotation.py
- apps/stable_diffusion/src/utils/utils.py
config located at [gs://shark_tank/sd_tuned_configs/unet_v1_4_fp16_vulkan_rdna2_512x512.json](https://console.cloud.google.com/storage/browser/_details/shark_tank/sd_tuned_configs/unet_v1_4_fp16_vulkan_rdna2_512x512.json;tab=live_object)
```
Loading Winograd config file from  C:\Users\ean\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.60kB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 3.20kB/s]
Loading lowering config file from  C:\Users\ean\.local/shark_tank/configs\unet_v1_4_fp16_vulkan_rdna2_512x512.json …
```
> [SD] (RDNA2) Enable new tuning for sd1.4

- apps/stable_diffusion/web/ui/stablelm_ui.py
https://github.com/nod-ai/SHARK/commit/8c219604861a2b9a349fe645d91e253022256f93 broke UI/Web on startup as it doesn't take into account the fact that it is possible for ones machine to not have any cuda devices.
This handles that case.
* Since I don't have any cuda devices, I haven't tested whether this does what we want when you do, although it should if https://github.com/nod-ai/SHARK/commit/8c219604861a2b9a349fe645d91e253022256f93 was correct there.
* Blocks both vircuna and stabilitylm if no cuda. I don't know whether this is correct for stabilitylm.
> Prevent having no cuda devices for LLM breaking the UI

- shark/shark_importer.py
This addresses (https://github.com/nod-ai/SHARK/issues/1522)
* The two with blocks in add_upcast appear to be underindented making SD 1.4 break on rdna3 per @monorimet, I've pushed them out one more tab, and then everything appears to work again.
Disclaimer: I have no idea what this code does other than the indents looking wrong and that's where it breaks.
> Fix (?) indents in add_upcast in shark importer

- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
Some fixes I could cherry pick from a local branch I was using 3.32.0 on, a quick look says these two problems still occur in 3.34.0.
* Fixes randomize seed buttons that stopped working.
* Update now deprecated method to set initial columns for output gallery to the newer undeprecated one.
> Some Fixes for update to gradio 3.34.0

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
I was not getting the same images using the same parameter info, before and after https://github.com/nod-ai/SHARK/commit/b20411356344e3810eb1bce29f2689ebaad8723b was merged.
It seems that when you specify `--max_length=77`, unet512 is *always* used, and that, in combination whatever adjustments are then made to the processing of prompt embedding so that they can be passed in to that unet version, results in different images.
This does not happen with the default of `--max_length=64`.
* Switches a few places in the SD pipeline, where an assumption of max_length=64 was being made, over to using the actual max_length as passed into the pipeline. This prevents unet512 and the accompanying prompt always being used when `--max_length=77`
* I don't know whether we would expect `unet512` to give …
> Fix unet512 always being used when --max_length=77

- apps/stable_diffusion/src/utils/utils.py
- shark/examples/shark_inference/mega_test.py
Add patch for making compile API work for both MEGABYTE and MiniGPT4
This adds add an optional `device` argument to the compile API.
> Add patch for making compile API work for both MEGABYTE and MiniGPT4

- shark/iree_utils/compile_utils.py
- shark/shark_inference.py
- shark/shark_runner.py
-- This commit is based on [VmModule.mmap() API](https://github.com/openxla/iree/pull/14124).
-- It thereby adds capability to mmap vmfbs in SHARK.
> [SharkInference-SharkRuntime] Adds capability to mmap vmfbs

- shark/shark_eager/shark_eager.py
- shark/shark_importer.py
-- Eager mode with step by step op compilation and execution.
> Add shark_eager mode.

- apps/language_models/scripts/vicuna.py
- apps/language_models/src/model_wrappers/vicuna_sharded_model.py
- apps/language_models/src/pipelines/vicuna_sharded_pipeline.py
you can now pass a config file generated with github.com/nod-ai/SHARK/blob/main/shark/shark_generate_model_config.py
> added ability to use config file to shard vicuna

- apps/stable_diffusion/web/ui/inpaint_ui.py
- rest_api_tests/api_test.py
This PR contains 2 one-liner patches for the inpainting rest api and tests for the same.
> [Blender Integration] Fixed Inpainting REST API

- apps/language_models/src/pipelines/vicuna_pipeline.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
Reverts nod-ai/SHARK#1587 The output doesn't seem to work. Lets land with the right fix without the spaces.
> Revert "[vicuna] Add streaming of tokens"

- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- rest_api_tests/api_test.py
1. Fixed outpaint api
2. Fixed txt2img api
3. Added tests for both
4. used `next(...)` to convert generator to subscriptable in other apis
> Final REST API Fixes

- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/utils/metadata/csv_metadata.py
- apps/stable_diffusion/web/utils/metadata/format.py
Addresses https://github.com/nod-ai/SHARK/issues/1583
https://github.com/nod-ai/SHARK/commit/44a8f2f8db469a99ee018cfc727a2f8ccf2d9866 added VAE & LoRA information to the .png metadata, .json files and the .csv file. The output gallery got the .png metadata updates for 'free' because it can use the same parser as the txt2img image drag and drop UI.
However, the update didn't cover the metadata parsing used by the output gallery to get the parameter information when .png metadata isn't present and it falls back to the .json and csv files. 
* Update saving of `img_details.csv` to include headers for the first row when creating new .csv files. 
* Update parsing of parameter info by the output gallery from `img_details.csv` to use headers when they are present. This and the above should make …
> Fix output gallery parameter info when sourcing from .csv and .json formats including VAE & LoRA

- apps/stable_diffusion/web/index.py
Running in app mode, you can't select any text that isn't part of an input control. This makes parameter info on the output gallery a lot less useful since you can't copy and paste it. This is different from how things work in web mode.
* When defining the webview window for App mode, set it up to allow text selection, as disallowing it is the default.
> UI/App - Allow text selection of non-inputs in app mode

- shark/iree_utils/compile_utils.py
- shark/iree_utils/cpu_utils.py
- shark/parser.py
by default. Can be overriden with a flag of the same str
> set task_topology_max_group to cpu_count

- shark/examples/shark_inference/mega_test.py
- shark/shark_compile.py
-- This commit adds a compile API in SHARK for quick testing of inference
models.
> [SHARK] Add a compile API to use for quick testing of inference

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
Addresses #1457 
There is small but noticeable difference in generation speed between running with the UI minimized and with it not, in favor of the minimized case. This is also seen if you size the app or browser window such that the gallery showing generated images is outside the browser viewport. 
In addition, currently the `no-progress_bars` command-line option doesn't appear to improve speed after the first image in the batch, I'm guess something changed with the upgrade to gradio 3.34.0 there.
All these looks like they are being caused by the two CSS animations that are run by gradio during generation, the 'sweep across the gallery' animation you get during the first image generation of a batch, and the 'pulsing border' animation you get on both the gallery and the generation status …
> UI/Web: Reduce animation of default --progress_bars setting to improve speed

- apps/stable_diffusion/scripts/train_lora_word.py
- apps/stable_diffusion/scripts/upscaler.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_inpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
- apps/stable_diffusion/src/schedulers/sd_schedulers.py
- apps/stable_diffusion/src/utils/resources/prompts.json
- apps/stable_diffusion/src/utils/sd_annotation.py
- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- apps/stable_diffusion/web/ui/utils.py
- fix overflowing text (a janky fix).
- increase prompt and negative prompt input box sizes to 2 lines so long default prompts don't get cut off.
- set window size to 81% monitor width and 91% monitor height since it fits the screen better than doing a non-maximized window at the monitor's full resolution. would be better to just maximize the window on launch, but I can't figure that out yet.
- add `DEISMultistep`, `DPMSolverSingleStep`, `KDPM2AncestralDiscrete`, & `HeunDiscrete` schedulers as an option.
- set default prompt to something different/newer (maybe we could change it every stable release, or every couple stable releases to spice things up?).
- set default negative prompt to something different/newer.
- set default CFG to 3.5 (may be a little low for some people, but I find …
> minor fix, some changes, some additions, and cleaning up

- .flake8
- .gitignore
- apps/language_models/scripts/vicuna.py
- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/models/opt_params.py
- pyproject.toml
-- This commit reverts the formatting for Brevitas op.
-- It also excludes vicuna.py script from `black` formatter.
> [Vicuna] Revert the formatting for Brevitas op

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- dataset/annotation_tool.py
Since Gradio is now unpinned I'm getting Gradio 3.36.1 as the latest, which has broken some stuff cosmetically and caused a lot of warnings on startup due to the deprecation of `.style` on controls.
* Clear .style deprecation warnings.
* Re-remove download button from Nod logos.
* Add work around for `container=false` not doing what it did before on dropdowns to the output gallery CSS
* I've not linted with black prior to check-in as for some reason `block --check .` locally has it suddenly deciding to lint my entire `shark.venv` when I do that and I have kill as it hits 100% CPU.
* Only works around the `container=False` problem for the output gallery. This setting was also used on the Chatbot and (I think!) other places, so those get whatever the gradio current styling for that case.
> UI/Web: Some Fixes for Gradio 3.36.1

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/utils/metadata/display.py
- apps/stable_diffusion/web/utils/metadata/format.py
_This contains code for Mac and Linux which I have not tested so I don't know is correct. Plus the whole concept feels pretty half-assed to me, but then again I keep running from the branch I have it on and **using** the thing. And continually rebasing it. Soooo PR._ 
It would be useful to be able to mark images in the output gallery and then filter them in or out of the gallery. Also at some stage move the ones you don't want somewhere else so they can be deleted (or move the ones you want to keep somewhere else, so you can delete what's left). I was trying to think of the simplest ways to do that whilst having the filtering persist between runs, and one of the ways I thought of was 'having marking an image move it to another subdirectory, and unmarking it move it back'.
This is not …
> UI/Web Output gallery - add 'open folder' button (needs Mac/Linux testing)

- apps/stable_diffusion/web/ui/outputgallery_ui.py
I regressed one of fixes for gradio deprecations, whilst resolving a merge conflict with https://github.com/nod-ai/SHARK/pull/1634
* Refix the remaining gradio deprecation warning in output gallery I regressed when resolving a merge conflict.
> UI/Web Refix remaining gradio deprecation warning

- apps/stable_diffusion/shark_sd.spec
- apps/stable_diffusion/shark_studio_imports.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/studio_bundle.spec
- build_tools/bundled_app_to_zip.py
- Run `pyinstaller .\apps\stable_diffusion\studio_bundle.spec -y` to build a single-directory application for SHARK
- Run `python .\build_tools\bundled_app_to_zip.py` to build a zip file in the main directory
onefile exe applications are still created in the same way they were before: `pyinstaller .\apps\stable_diffusion\shark_sd.spec`
Reason:
`--onefile` and `--onedir` are commands that pyinstaller accepts when it is pointed to a python script. These commands dictate how a spec file is created. Once the spec file is created, it will produce either a folder or an exe file depending on how the spec file was configured
Hence, if we want our build commands to point to spec files (because it allows us to use hidden imports and pyinstaller hooks without writing an unwieldy shell command) we …
> Added support for building ZIP distributions

- tank/examples/opt/opt_perf_comparison.py
mostly pulled from [this script](https://github.com/godot73/mlir-toy-bazel/blob/main/examples/shark/opt_comparison.py)
the script is all-inclusive -- it will import and compile the vmfb for OPT1.3b and compare against pytorch, generating perf comparison between SHARK/IREE and pytorch.
> add perf comparison script for opt.

- apps/language_models/scripts/vicuna.py
moved the unpack quantized weights pass from vtensor canonicalize pass to a separate pass
https://github.com/llvm/torch-mlir/commit/ee3a9281c73eda5330138d336a970b8d74cf0cbb
> Change to a separate pass to unpack quantized weights

- apps/stable_diffusion/scripts/inpaint.py
- apps/stable_diffusion/scripts/outpaint.py
- apps/stable_diffusion/scripts/txt2img.py
- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
Partially addresses https://github.com/nod-ai/SHARK/issues/1351
When dialing in prompts I often want to see multiple images with my prompt changes, but also compare them to images generated with a previous prompt, currently this requires you to generate an single image at a time, entering each seed one by one.
These changes allow you to set batches to use the same set of seeds as a previous set of batches when the first batch has the same starting seed. You can then re-run those batches with each batch getting the same seed as before.
* Generates the seeds for all batch_count batches being run up front rather than generating the seed for a batch just before it is run.
* Adds a --repeatable_seeds argument defaulting to False
* When repeatable_seeds=True, the first seed for a set of batches …
> SD - Add repeatable (batch) seeds option

- apps/stable_diffusion/shark_sd.spec
- apps/stable_diffusion/shark_studio_imports.py
- apps/stable_diffusion/studio_bundle.spec
Pyinstaller was failing with some import erros as the [langchain PR](https://github.com/nod-ai/SHARK/pull/1657/files) assumes that the root is the langchain folder. This is not an issue when running outside of exe because of [this line](https://github.com/nod-ai/SHARK/blob/ab01f0f048ee9b8cd4fea463461f148bf0904d17/apps/language_models/langchain/gen.py#L28). However, it does not have the intended effect in pyinstaller.
> Pyinstaller Path Patch

- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
Addresses those parts of https://github.com/nod-ai/SHARK/issues/1351 remaining after https://github.com/nod-ai/SHARK/pull/1654
Sometimes you want to run batches with a list of already known seeds. This implements that by allowing you to pass an array of integers in JSON format as the seeds argument either from the command line or within the SD UI.
* SD Scripts and UI tabs that support batch_count can now take a string containing a JSON array, or a list of integers, as their seed input as an alternative to just an integer.
* Each batch in a run will now take the seed specified at the corresponding array index if one exists. If there is no seed at that index, the seed value will be treated as -1 and a random seed will be assigned at that position. If an integer rather than a list or json …
> SD - Implement seed arrays for batch runs

- apps/stable_diffusion/web/index.py
With all the new tabs, the order of them has gotten into a bit of a tangle. This tries to tidy things up a bit.
* Move `Output gallery` tab immediately after `Upscaler`.
* Move `LoRA Training` to be the first of the experimental tabs after `Model Manager`.
* This keeps the tabs relating to SD together (assuming Model Manager is SD), the Experimental Tabs together, and the LLM tabs together.
* Conflicts with [#1700](https://github.com/nod-ai/SHARK/pull/1700) which adds...Yet another tab.
* I was tempted to add the `(Experimental)` tag to the Model Manager given its current state. But I didn't.
> UI/Web: Reorder tabs to separate/group SD, LLM and Experimental

- apps/language_models/langchain/make_db.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/__init__.py
- apps/stable_diffusion/web/ui/h2ogpt.py
This adds an upload tab for DocuChat. With this the only remaining UI work is to plumb in the precision selector.
> Change the DocuChat web UI

- apps/language_models/langchain/gpt_langchain.py
Just before a686d7d89f55bb0d5f918a995df1ed98e7e9e73a which temporarily disabled DocuChat/langchain I was getting the following error, when running the ui/web after manually installing the `langchain` dependency:
```
Traceback (most recent call last):
File "C:\develop\SHARK\apps\stable_diffusion\web\index.py", line 94, in <module>
from apps.stable_diffusion.web.ui.utils import create_custom_models_folders
File "C:\develop\SHARK\apps\stable_diffusion\web\ui\__init__.py", line 82, in <module>
from apps.stable_diffusion.web.ui.h2ogpt import h2ogpt_upload, h2ogpt_web
File "C:\develop\SHARK\apps\stable_diffusion\web\ui\h2ogpt.py", line 15, in <module>
from gpt_langchain import (
File "C:\develop\SHARK\apps\language_models\langchain\gpt_langchain.py", line 418, in <module>
class …
```
> fixes for pydantic in gpt_langchain.py

- shark/iree_utils/_common.py
- shark/iree_utils/compile_utils.py
- shark/iree_utils/cpu_utils.py
- shark/iree_utils/gpu_utils.py
- shark/iree_utils/metal_utils.py
- shark/iree_utils/trace.py
- shark/iree_utils/vulkan_target_env_utils.py
- shark/iree_utils/vulkan_utils.py
* Various fixes to add `@functools.cache` to what should be one time, expensive, device enumeration and setup activities. Cuts several seconds off of initialization on my machine.
* Add detailed tracing to actual invocations if they exceed a certain timeout or have an exception.
* Add detailed tracing to loading status.
* By default detail logging is only printed if an operation takes an excessive amount of time. All logging/timing can be printed by setting the variable `$env:SHARK_DETAIL_TRACE = "1"`
> Optimize device enumeration overhead and log details on long operations.

- apps/stable_diffusion/web/index.py
Tab order has gone back to being messy again.
* Reverts the tab order, so that SD, LLM, and Experimental are grouped together again as far as is possible.
* Labelled "Generate Sharding Config" as experimental as pressing the 'Get Model Config' errors for me.
* Perhaps "Get Model Config" is working for other people?
* "Generate Sharding Config" probably could do with moving before "Chat Bot" or right to the end. But I left it where it is.
> UI/Web - Revert tab order

- apps/language_models/scripts/vicuna.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
- required for passing target triple from command line when running LLMs on web and cli
- NOTE:
- target triple for Sharded LLMs is experimental as of now.
- duplicate args from SD and LLMs will need to be refactored into a more disjoint set of cli args to prevent the argparse objects from eating up each others values when used in the same file.
> add support passing iree flags for  LLMs

- apps/language_models/scripts/vicuna.py
- apps/language_models/shark_llama_cli.spec
This PR adds 2 separate commits :-
1. Fixing issues with downloading/crashing of Llama2 13B - previously I was adding another flag but later saw that there is an unused one + had to change the order of downloading of the files.
2. A spec file to run CLI exe of Llama2 - the CLI spec file for SD misses out on couple of dependencies needed for Llama, so I created a separate one to not disturb the SD path.
> Fix llama2 13b crashing + add spec file for CLI execution of Llama

- apps/language_models/scripts/vicuna.py
fixes the following error which occurs when on compilation of llama2_70b generated from vicuna.py
```
<stdin>:39854:25: error: use of value '%arg1' expects different type than prior uses: 'tensor<1x60x?x128xf16>' vs 'tensor<1x8x?x128xf16>'
%dim_4_int = tensor.dim %arg1, %c2 : tensor<1x60x?x128xf16>
```
> fix llama2-70b rewrite tensor dim

- setup_venv.sh
This fixes torchvision model generation when torch-mlir has an older torch version as requirement. The torchvision pip install will rerun with the version of torch installed by torch-mlir if IMPORTER=1 is specified.
> Fix torchvision versioning in Linux importer setup.

- .gitignore
- apps/language_models/scripts/vicuna.py
-- This commit prefetches llama2 tokenizer configs from shark_tank.
The configs are from [daryl149/llama-2-7b-hf](https://huggingface.co/daryl149/llama-2-7b-hf) and I've verified it with the MLIR files for llama2 which we've generated from [meta-llama/Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf).
> [Llama2] Prefetch llama2 tokenizer configs

- apps/stable_diffusion/shark_studio_imports.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
- apps/stable_diffusion/src/utils/sd_annotation.py
Also disables vae tuning for RDNA3.
> (SD) Fix tokenizers imports in pyinstaller builds.

- shark/iree_utils/compile_utils.py
- shark/parser.py
This allows to pass more arguemnts to the IREE compiler Example:
python my-app.py --additional_compile_args="--mlir-pretty-debuginfo --mlir-timing"
> Add argument --additional_compile_args

- apps/language_models/scripts/vicuna.py
- apps/language_models/utils.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
- shark/iree_utils/vulkan_utils.py
-- This commit fixes the wrong Vulkan device being selected during
runtime.
-- It also adds couple of IREE compilation flags to target specific
Vulkan device.
-- It also changes the Vulkan device listing to be in tune with the lowering
control flow.
> [Llama2] Fix wrong Vulkan device ID + Add Vulkan compile flags

- apps/stable_diffusion/src/utils/utils.py
Latest version of diffusers used by pip on fresh install changes the parameter name. Updating file reference to match.
> Fix checkpoint_path unexpected argument

- shark/iree_utils/compile_utils.py
-- Currently SHARK suggests that vmfb has been saved, while
that is not the case and no vmfb is generated. 
This creates a misdirection for IR/vmfbs which are of larger
size.
-- This commit therefore fixes that misdirection.
> Fix misdirection while saving vmfb

- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/src/utils/utils.py
This is really just a temporary solution to piping these kinds of IREE runtime options from SHARK Studio.
We should probably just allow the specification of `iree_runtime_args` to be piped down in a device-agnostic fashion instead of naming them here in stable_args or in shark_args (worse), though it does help to have a curated list of knobs to tweak for users.
Currently only piped through for Vulkan devices.
I have a better implementation of supplying runtime args to the core SHARK python runtime utils in progress here: https://github.com/nod-ai/SHARK/pull/1855 but it still needs some work.
> Add flag for specifying device-local caching allocator heap key.

- apps/stable_diffusion/shark_studio_imports.py
Adds diffusers submodules to hidden imports to force pyinstaller to pick up the SD pipeline modules needed for checkpoint preprocessing.
> (Studio) Collect pipeline submodules for diffusers ckpt preprocessing.

- shark/iree_utils/compile_utils.py
Print a note ahead of a potentially long inactivity to set the right expectations.
Separately, it seems possible to make this loading significantly faster.
> [vulkan] Print note about module load times. NFC.

- apps/language_models/scripts/vicuna.py
Add flags to enable a non-internactive mode for microbenchmarking llama models. In this mode, the system and user prompts are specified with CLI flags, and the number of generated tokens and iterations is fixed.
Also move the stats below the response and trim any response blankspace.
> Add microbenchmark mode to vicuna CLI

- apps/language_models/scripts/llama_ir_conversion_utils.py
-- This script adds a standalone utility for converting Llama IRs to dynamic and combining them as well.
```
This script can be used as a standalone utility to convert IRs to dynamic + combine them.
Following are the various ways this script can be used :-
a. To convert a single Linalg IR to dynamic IR:
--dynamic --first_ir_path=<PATH TO FIRST IR>
b. To convert two Linalg IRs to dynamic IR:
--dynamic --first_ir_path=<PATH TO SECOND IR> --first_ir_path=<PATH TO SECOND IR>
c. To combine two Linalg IRs into one:
--combine --first_ir_path=<PATH TO FIRST IR> --second_ir_path=<PATH TO SECOND IR>
d. To convert both IRs into dynamic as well as combine the IRs:
--dynamic --combine --first_ir_path=<PATH TO FIRST IR> --second_ir_path=<PATH TO …
```
> [Llama2] Add a standalone utility for dynamic and combining IRs

- apps/language_models/scripts/vicuna.py
Print averaged results at the end of all iterations. Increase the default number of iterations to 5.
Example:
```
Number of iterations: 5
Prefill: avg. 0.03 s, stddev 0.00
Decode: avg. 43.34 tokens/s, stdev 0.13
```
Also remove the -2 in the number of generated tokens -- I did not find any evidence we need it.
> Add aggregate statistics to microbenchmark

- apps/stable_diffusion/src/schedulers/shark_eulerdiscrete.py
- apps/stable_diffusion/src/utils/utils.py
- setup_venv.sh
- shark/iree_utils/metal_utils.py
- fix setup_venv issues (removes `timm` only for MacOS to avoid conflicting torch-mlir and torch versions due to torchvision dependency)
- remove unused iree compilation flags for  MacOS
- clean metal compilation args
> Macos fixes 

- apps/stable_diffusion/src/utils/utils.py
With repeatable seeds selected, I ran a set of three batches of one image in Txt2Img, followed by a set of six batches of one image, using the same starting seed.
Images 2 and 3 of set 1 were not the same images as 2 and 3 of set 2, and were logged as having used different seeds.
Although each batch set of the same length with the same starting seeds generates the same sequence of seeds, batches of different lengths don't match up after the initial seed. This is not what I was expecting.
(I did this from the UI, but that shouldn't be significant)
* Set the input seed for the random number generator when generating repeatable seeds to exclude any negative numbers in the parsed seed input including placeholder ones for subsequent batches.  This makes seeds generated for different batch …
> SD: Fix repeatable seeds consistency over different batch counts

- apps/stable_diffusion/src/utils/utils.py
I ran a set of batches with repeatable seeds set, with initial seed set to -1.
I then immediately afterward ran another set of batches with repeatable seeds set, again with the initial seed set to -1.
I expected to get a completely different set of images and seeds for each set of batches, because the initial seed generated for each set should have been different due to the -1 being replaced with a new random seed each time. However I got the exact same set of seeds and the same images.
The cause of this is that the rng state is being saved for repeatable seeds before the first seed is generated, rather than after.
(I did this from the UI, but that shouldn't make a difference)
* When repeatable seeds is set, but only random seeds are requested, generate the initial seed before seeding the …
> SD: Fix repeatable seeds when initial seed should be random

- README.md
- shark/examples/shark_inference/ESRGAN/esrgan.py
- shark/examples/shark_inference/albert_maskfill_tf.py
- shark/examples/shark_inference/bloom_tank.py
- shark/examples/shark_inference/mhlo_example.py
- shark/examples/shark_inference/minilm_jit.py
- shark/examples/shark_inference/resnest.py
- shark/examples/shark_inference/resnet50_fp16.py
- shark/examples/shark_inference/simple_dlrm.py
- shark/examples/shark_inference/sparse_arch.py
- shark/examples/shark_inference/unet_script.py
- shark/examples/shark_inference/v_diffusion.py
Follow https://github.com/nod-ai/SHARK/pull/708, remove parameter 'func_name' for SharkInference.
> SharkInference: Fix various examples and README.md

- .gitignore
- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/civitai.py
While testing https://github.com/nod-ai/SHARK/pull/1906 I found that entering Civitai api download urls into the webui wasn't working for me. This was due to the code trying to launch a subprocess to `wget` which is not guaranteed to be (and probably isn't) installed on windows, so everything falls over there.
Once I had something working in Python to do the download instead, I discovered a number of other problems with the civitai download, mainly to do with naming being taken from the civitai id number rather than the correct filename of the model file.
This PR should address most of this.
* Move civitai model download into Python code rather than make a subprocess call to wget, as wget usually won't exist on Windows.
* Save model files downloaded from civitai under the correct filename …
> SD - Fix civitai download on Windows +other civitai download improvements

- apps/stable_diffusion/src/utils/resources/opt_flags.json
- apps/stable_diffusion/src/utils/sd_annotation.py
Addresses #1902.
https://github.com/nod-ai/SRT/commit/b7fd66860adf5a2fcd6b61c7cbbbe64f33474cd7 moved two iree pass-pipeline options we are using from being in `flow` to being in `global`. This caused pre-processing to fail and the resulting .vmfbs to have a very large performance regression (~20it/s -> ~4it/s on 7900 XTX).
This updates everywhere we've used these to the new naming (I think!).
* updates the following iree preprocessing passpipline arguments wherever they appear in the code, as their naming has changed in SRT:
* `iree-flow-detach-elementwise-from-named-ops` -> `iree-global-opt-detach-elementwise-from-named-ops`
* `iree-flow-convert-1x1-filter-conv2d-to-matmul` -> `iree-global-opt-convert-1x1-filter-conv2d-to-matmul`
* I have no idea what any of this that I've changed …
> Fix MLIR Textual PassPipeline Error

- apps/stable_diffusion/web/ui/stablelm_ui.py
Following the template outlined [here](https://huggingface.co/blog/llama2#how-to-prompt-llama-2). This should get the chat to function properly and not act weird responding along the lines of `It seems you are trying to send HTML tags.`
Without these changes it will send a message of `Hello` as follows:
```
[INST] <<SYS>>
<</SYS>>
Hello [/INST]  
```
While the correct formatting is as follows:
```
[INST] Hello [/INST]
```
This also removes the `System:` prefix to the system prompt as it's not needed, and also will only add `<<SYS>>` & `<</SYS>>` if the system prompt is actually being used.
There are also BOS and EOS tokens which should be applied to the template I think, but I'm unsure if those are automatically added yet so I didn't add that yet.
> LLaMa 2 Chat template fix

- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
I should have done this when I made the original changes to the `txt2img` buttons.
> Position `Generate`, `Randomize Seed`, & `Stop Batch` buttons to match `txt2img` tab

- apps/stable_diffusion/src/utils/resources/opt_flags.json
I didn't make the correct change to the untuned opt_flags for unet in #1910 😬
* correct my sloppy copy/paste for the untuned unet default compilation flags that introduced an extra 'detach' into what should have been 'iree-global-opt-convert-1x1-filter-conv2d-to-matmul'
* ROCM is actually slower with these flags than having them broken. ~1.75 it/s broken, ~1.5 it/s with this fix for a SD 1.5 based model.
> SD: Fix unet untuned opt_flags

- shark/iree_utils/gpu_utils.py
- on passing rocm args from cli, cannot use caching.
> remove caching for iree rocm args

- apps/language_models/scripts/vicuna.py
Add a new flag `--Xiree_compile` to forward extra compiler arguments to `iree-compile`. This flag can be set multiple times to pass more than one extra argument.
> [vicuna.py] Allow to pass extra arguments to iree-compile

- apps/stable_diffusion/src/utils/stable_args.py
For stability, until these two features have been updated and are once again functional on nightly releases, disable UNet tunings to workaround linalg IR changes and disable shark_tank downloads until the turbine SD pipelines are set up and we can generate the correct artifacts for the updated stack.
> (Studio) Disable SD tunings and sub-model downloads

- apps/language_models/scripts/vicuna.py
- shark/iree_utils/compile_utils.py
- shark/iree_utils/vulkan_utils.py
- add fixes for device selection on vulkan
- also this removes the forced ordering of devices based on device_path and now relies on device ordering from iree to be consistent across reboots (user should ensure selecting the correct device index for the current session)
> fix vicuna cli vulkan path

- shark/iree_utils/compile_utils.py
compile_str is always False in compile_module_to_flatbuffer since there is a parameter 'model_name' before 'debug'.
This issue is relative to https://github.com/nod-ai/SHARK/pull/1863.
Then we can use mlir model buffer in RAM to run inference.
> Fix wrong parameter index passed to 'compile_module_to_flatbuffer'

- apps/language_models/scripts/vicuna.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
- shark/iree_utils/compile_utils.py
- drivers with single device will not be shown with `://0` indexing
- plumb metal device through chatbot execution (currently the default metal device is selected)
> Fix MacOS web execution flow

- shark/iree_utils/_common.py
- shark/iree_utils/gpu_utils.py
- add support for getting rocm arch using `iree-run-module --dump_devices=rocm`
- assumption - order of devices in `iree-run-module --dump_devices=rocm` and `iree.runtime.get_driver("rocm").query_available_devices()` is the same on the system.
- the filtering of the dump info is heavily dependent on its format.
> fix rocm arch selection

- apps/stable_diffusion/web/utils/app.py
Hopefully addresses #1962
My changes for https://github.com/nod-ai/SHARK/pull/1952 have broken webui startup on Linux (and I assume Mac as well).
* Moves the imports of winreg and Tk, into the functions that use them, with winreg behind a guard clause. This should hopefully mean that if you're not on Windows or not using `ui=app` we won't trip over either of these due to them not being there.
* I'm not on Linux or Mac, so I can't test that this actually does the job.
* CI not working right or not covering webui startup biting here...?
> UI: Fix webui launch on non-Windows

- requirements.txt
pyinstaller-hooks-contrib doesn't see beta versions of pydantic as versions greater than 2.0.0, and so it looks for an attribute `compile` only available in versions older than 2.0.0 if you have a beta version of pydantic.
This returns an error and causes the pyinstaller build to fail, so pin pydantic to 2.4.1 until the hook is fixed.
> Pin pydantic to 2.4.1 in requirements

- docs/shark_sd_koboldcpp.md
* Fix the image link for the koboldcpp style button pointing to the dialog image rather than the button image.
> API/Docs: Fix an image link in koboldcpp doc

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
- apps/stable_diffusion/src/utils/__init__.py
- apps/stable_diffusion/src/utils/resamplers.py
- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
Hires fix and Image2Image kept blowing up on me because a number of the current resampler options don't exist in PIL which is what the code uses to do the resampling.
Also, since the UI for hires fix uses image2image to do the resize but uses the scheduler you select for text2image, it would blow up again, due to the default there being 'SharkEulerDiscrete' and image2image only working with the CPU schedulers.
This should prevent those problems.
* Restrict resamplers for img2img and high res fix to the ones that PIL.Image actually supports, since we uses that to do the resampling. Removed: Antialias, Affine, Cubic. Added: Hamming.
* Set list of available schedulers to CPU only when high res fix is selected in the web ui. Set list to all schedulers when high res fix is deselected.
* Put hi …
> SD/UI Restrict hires fix/img2img resamplers/schedulers

- apps/stable_diffusion/src/utils/stable_args.py
- shark/model_annotation.py
It seems there is some lowering pass pipeline change for the matmul dispatches. Since the tunings for matmuls in SD is less performance-impactful than other ops, re-enable tunings for ops other than matmuls.
This bumps inference speed on my 7900xtx back up to ~22it/s
> Re-enable SD tunings without matmuls.

- apps/stable_diffusion/web/ui/common_ui_events.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- apps/stable_diffusion/web/ui/utils.py
Since I can't remember what most of the LoRAs sitting in my `./models/lora folder` do, given their cryptic filenames, the chances of my coming up with the trigger words for them, are, by now, completely non-existent.
So this tries to give some indication for what they might possibly be for LoRAs in .safetensors format. It does this by querying for training metadata in the format written out by https://github.com/kohya-ss/sd-scripts. If it finds some it them displays the tags used on at least 65% of the images trained, ordered by frequency with their borders colored from green (most common) to red (least common).
It also gives an indication of the model trained against (short hash/filename) if that information is present.
* Adds a function to webui utils to read metadata from .safetensors …
> UI: Display top tag frequencies and model trained against when a LoRA is selected

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/outputgallery_ui.py
The Gradio version we have pinned allows removal of my original crufty code to manage the number of gallery columns in the output gallery, but also needs a workaround for some inappropriate scrollbar visibility on the parameters pane on the same tab.
So this does that.
* Workaround gradio bug that causes the parameters frame to always show scrollbars.
* Remove the original funky method of setting the number of image columns in the gallery using _fn= JavaScript events. The version of gradio we now have pinned allows doing this by setting the property on the gallery directly and also doesn't keep resetting the columns on other events being fired, so we no longer need to workaround that by re-setting the columns every time that happens.
> UI: Output galllery cleanups

- docs/shark_sd_koboldcpp.md
Turns out I didn't update the REST api document for connecting to Joboldcpp with a change I made during development to the naming of the command line argument that sets CORS origins, and didn't notice this because I run the API via a script which uses the updated argument.
* Replace `api_cors_origin` in the api/koboldcpp doc, with the correct `api_accept_origin`
> API/Docs: Fix incorrect cors arguments listing

- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/stablelm_ui.py
- setup_venv.ps1
- add torchvision to setup_venv.ps1 -- we need this for the torchvision::nms that is now a dependency of controlnet features.
- Don't have bad flashy orange updates when using the chatbot
- Don't limit the height of the chatbot -- there's mixed opinions and solutions around this one. I think the default (400) is just way too small and LLMs generate plenty enough to justify matching the output.
> Small UI tweaks for chatbot, fix torchvision requirements

- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/ui/stablelm_ui.py
- shark/iree_utils/compile_utils.py
- shark/iree_utils/vulkan_utils.py
- shark/shark_importer.py
- saves temp .mlir files to ./shark_tmp/ instead of system /tmp/ (causes issues on linux and some windows envs)
- fixes multigpu cases for vulkan device selection
> Use clean_device_info() by default and don't write .mlir to /tmp/

- shark/iree_utils/gpu_utils.py
- when compiling, the device index passed is None, set it to default index - 0
> quick fix rocm `None` device err

- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/utils/tmp_configs.py
d051c3a4a7a7cdf645899e05439ccf782fe37b37 moved generation of intermediate `.mlir` files into `./shark_tmp`. This includes them in the deletion of files we already do for gradio temporary image files on studio start.
* Add .mlir to the fiiles that are deleted from `./shark_tmp` when studio is started.
* refactor/rename existing gradio temp file cleanup on startup to be consistent with a general `./shark_tmp` cleanup
> Add .mlir to startup shark_tmp cleanup

- .github/workflows/test-models.yml
- shark/iree_utils/compile_utils.py
- shark/iree_utils/vulkan_utils.py
- shark/shark_importer.py
shark_importer's `save_mlir` fails if the directory doesn't exist. Create it if this is the case.
Soft fail a100 SD CI as image similarity check is expected to fail at the moment.
> Create specified dir if needed during save_mlir and fix vulkan device fetching without URI/ID

- apps/language_models/scripts/vicuna.py
- Move statistics out of the main loop
- Calculate the input prompt token count. Note that this includes the stop token, e.g., 'Hi' is counted as 2 tokens.
- Add 'end-to-end' numbers
- Switch the main display unit from s to ms
- Start measuring time at 0
The new print format looks like this:
```
Number of iterations: 5
Num tokens: 1 (prompt), 512 (generated), 513 (total)
Prefill: avg. 0.01 ms (stdev 0.00), avg. 97428.99 tokens/s
Decode: avg. 4840.44 ms (stdev 28.80), avg. 97428.99 tokens/s
Decode end-2-end: avg. 105.78 tokens/s (w/o prompt), avg. 105.98 (w/ prompt)
```
> [vicuna.py] Rework benchmark statistics calculation

- shark/iree_utils/gpu_utils.py
The correct name for the architecture is gfx1100, not gfx_1100.
System is Debian testing, rocm 5.7, XFX MERC310 RX 7900 XTX
rocminfo output:
```
*******                  
Agent 2                  
*******                  
Name:                    gfx1100                            
Uuid:                    GPU-4b980329224432b7               
Marketing Name:          AMD Radeon RX 7900 XTX             
Vendor Name:             AMD                                
Feature:                 KERNEL_DISPATCH                    
Profile:                 BASE_PROFILE                       
Float Round Mode:        NEAR
--truncated--
```
SHARK before:
```
Configuring for device:rocm
could not execute `iree-run-module --dump_devices=rocm`
Did not find ROCm architecture from …
```
> Fix typo in default_rocm_arch

- apps/stable_diffusion/scripts/txt2img_sdxl.py
- apps/stable_diffusion/src/__init__.py
- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/models/opt_params.py
- apps/stable_diffusion/src/pipelines/__init__.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img_sdxl.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/src/utils/resources/base_model.json
- apps/stable_diffusion/src/utils/stable_args.py
- apps/stable_diffusion/src/utils/utils.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/__init__.py
- apps/stable_diffusion/web/ui/txt2img_sdxl_ui.py
-- This commit adds SDXL pipeline to SHARK.
> [SDXL] Add SDXL pipeline to SHARK

- apps/shark_studio/modules/embeddings.py
Better to make sure Studio2 has these fixes as we go, rather than port them across at a later date.
* Updates ProcessLoRA to use both embedded LoRA alpha, and lora_strength optional parameter (default 1.0) when applying LoRA weights.
* Updates ProcessLoRA to cover more dim cases.
* This brings ProcessLoRA into line with PR #2015 against Studio1
* I'm assuming the calls to missing functions is okay for the current state of the project, so I didn't try to sort out the existing call to `get_path_stem` on line 111.
> Studio2/SD: Use more correct LoRA alpha calculation

- apps/stable_diffusion/web/api/sdapi_v1.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/common_ui_events.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/inpaint_ui.py
- apps/stable_diffusion/web/ui/lora_train_ui.py
- apps/stable_diffusion/web/ui/model_manager.py
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/ui/txt2img_sdxl_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- apps/stable_diffusion/web/ui/utils.py
- dataset/annotation_tool.py
- requirements.txt
* Upgrade Gradio pin from 4.7.1 to 4.80.
* Make Nod AI logos visible again.
* Remove image toolbars from png import boxes.
* Set Input Images on img2img, outpaint and upscaler tabs to be upload only.
* Change Image control to an ImageEditor control for masking on the inpaint tab. Remove previous height restriction as this hides the editing controls.
* Move Input Image/Masked Image on img2img, inpaint, outpaint and upscaler tabs to be the first control on their tabs.
* Remove download buttons from all galleries as they download some html rather the image (gradio issue #6595)
* Remove add new row and column from Output Gallery parameters dataframe.
* Add partial workaround for not being able to select text in the Output Gallery Gallery parameters dataframe (gradio issue #6086 )
* Fix …
> UI: Fixes for Gradio 4.7.1/4.8.0 update 

- setup_venv.ps1
- setup_venv.sh
*This is for the SHARK-1.0 branch **only**, and any potential branches from that, do *not* merge into main branch*
I need a working SHARK 1.0 whilst SHARK 2.0 is being constructed, and I still have the draft of #2015 I'm working on for SHARK 1.0.  So I need separate .venvs for `main/studio_sd2` and `SHARK-1.0` branches.
Having a `setup_venv` on the SHARK-1.0 branch that creates/maintains a separately named .venv, means I can just run that and not worry I've broken the .venv for the other branches.
* Updates setup_venv.ps1 to create and use ./shark1.venv/
* Updates setup_venv.sh to default to creating ./shark1.venv/
* I haven't tested the `setup_venv.sh` change, someone on Linux/Mac will need to check that.
* I'm assuming we want to keep the main branch .venv as `./shark.venv/`
* I had …
> (Studio 1.0) Setup a separate `shark1.venv` for Shark-1.0

- apps/shark_studio/api/llm.py
- shark/iree_utils/compile_utils.py
This flag should be a model/use-case specific addition, not a default CPU compile flag.
We may need to add it to llama2 if it's required for compilation.
> Relocate quantized matmul reassociation flag

- apps/stable_diffusion/shark_studio_imports.py
- apps/stable_diffusion/web/index.py
- apps/stable_diffusion/web/ui/css/sd_dark_theme.css
- apps/stable_diffusion/web/ui/img2img_ui.py
- apps/stable_diffusion/web/ui/js/sd_gradio_workarounds.js
- apps/stable_diffusion/web/ui/outpaint_ui.py
- apps/stable_diffusion/web/ui/outputgallery_ui.py
- apps/stable_diffusion/web/ui/txt2img_sdxl_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
- apps/stable_diffusion/web/ui/upscaler_ui.py
- requirements.txt
Came back to SHARK for a bit to generate some images (using 1.0), to discover I somehow had a gradio version which broke UI sizing. Then I also noticed that dependabot wanted an upgrade to 4.11 for `main` branch. Looks like a security fix went into that version.
However latest gradio version pulled down by pip for me is 4.12, and that is also breaking UI sizing, so here's an upgrade to that for Shark 1.0, with a work around for the sizing problem. 
* Upgrade Shark 1.0 to gradio 4.12.0
* Add javascript workaround for gradio currently ignoring @media rules in custom CSS. This fixes UI not showing at full width on desktop (>1536px width).
* af4b9c744 Re-enable gallery download buttons as they are now fixed in Gradio.
* Workaround needs javascript shenanigans.
* I've added what I think is the …
> (Shark 1.0) UI: Upgrade to gradio 4.12.0 and fix breakage

- apps/stable_diffusion/src/models/model_wrappers.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img_sdxl.py
- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
- apps/stable_diffusion/web/ui/txt2img_sdxl_ui.py
- apps/stable_diffusion/web/ui/txt2img_ui.py
I tripped over some things when running running the `juggernautXL_v7Rundiffusion` model from the SDXL tab. This tweaks the UI tab with more immediately functional defaults, and tries to reduce the number of failed attempts at unet base model determination when doing initial .vmfb compilation, eliminating some cases where the wrong base model could be chosen. 
* SDXL Tab
* Filter VAEs in dropdown in the same manner as models.
* Set default VAE selection to 'madebyollin/sdxl-vae-fp16-fix'.
* Set default image size to 768x768 to match current Vulkan constraints
* SharkifySDModel Base Unet Model Determination.
* Alway use the model_to_run as the base model for unet, if that model is a base model defined in base_model.json. Skips looping through all possible base models before that model is …
> (Shark 1.0) UI/SD Some UX improvements for SDXL

- apps/stable_diffusion/web/ui/txt2img_ui.py
Looks like I left a keyword argument that shouldn't have been there in my last PR #2057 that got merged, breaking Text2Image.
* Removes the incorrect valid_base_models keywoard argument left in text2img_inf
> (Shark-1) UI: Fix 'keyword argument' error in txt2img

- package-index-torch-mlir.html
- setup_venv.ps1
Addresses #2061 
The version of torch-mlir pinned by d35288e seems to have dropped off of https://llvm.github.io/torch-mlir/package-index/ so `.\setup-venv.ps1` fails to install it.
* Adds a local file equivalent of https://llvm.github.io/torch-mlir/package-index/ containing links to the pinned torch_mlir versions (links taken from the torch-mlir releases github page).
* Use the local file instead of the real package index in setup_venv.ps1.
* I would be entirely unsurprised if this is completely the wrong way to handle this.
* Does change anything for the `setup-venv.sh` script as the original commit didn't touch that.
> (Shark 1.0) Fix setup_venv.ps1 not finding pinned torch-mlir

- apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
Inpainting and (presumably other non txt2img operations) is currently breaking at the point where a `SharkifyStableDiffusionModel` is constructed for the appropriate SD pipeline.
* Add the @classmethod decorator to the base implementation of `favored_base_models`. This stops running any SD pipeline that does not have a specific implementation of the method (everything but txt2img and txt2img_sdxl), breaking at the Sharkification stage.
> (Shark 1.0) SD: Fix inpaint (+others) breakage on sharkification

- README.md
When people just want an image generator its too easy for them to grab a not yet working Shark2 version from `main`, rather than getting SHARK-1.0.
This updates the README.md to tell them they should be using SHARK-1.0 for now.
- Add a note at the of the top of the README to use SHARK-1.0 whilst rewrite with Turbine is ongoing.
- Update installation section to point at SHARK-1.0 branch.
- Suggest the latest SHARK-1.0 pre-release as well as stable.
- Recommend running the .exe from the command line.
> Update README to recommend SHARK-1.0 for now

- apps/shark_studio/web/index.py
- apps/shark_studio/web/ui/css/sd_dark_theme.css
- apps/shark_studio/web/ui/js/sd_gradio_workarounds.js
- apps/shark_studio/web/ui/sd.py
- requirements.txt
I have eyes. 🤪 
* Update Gradio pin to 4.15.0.
* Port workarounds for Gradio >4.8.0 main container sizing from Shark 1.0.
* Move nod Logo out of the SD tab and onto the top right of the main tab bar.
* Set nod logo icon as the favicon (as current Shark 1.0).
* Create a tabbed right hand panel within the SD UI sized to the viewport height.
* Make Input Image tab 1 in the right hand panel.
* Make Output images, generation log, and  generation buttons, tab 2 in the right hand panel
* Make config JSON display, with config load, save and clear, tab 3 in the right hand panel
* Make gallery  area of the Output tab take up all vertical space the other controls on the tab do not.
* Tidy up the controls on the Config tab somewhat.
(Since https://github.com/nod-ai/SHARK/pull/2074/commits/a9836937817f …
> Studio2/SD/UI: Improve various parts of the UI for Stable Diffusion

- apps/shark_studio/api/sd.py
- apps/shark_studio/web/configs/default_sd_config.json
- apps/shark_studio/web/ui/sd.py
- apps/shark_studio/web/ui/utils.py
- setup_venv.ps1
_Amongst other things this address #2063 on Windows, but not necessarily in the correct way_
Get running the SD pipeline from the SD UI at least to the point where it breaks because I'm on Windows rather than for other reasons.
* Remove separate install of iree-runtime and iree-compile in setup_venv.ps1, and rely on the versions installed via the Turbine requirements.txt. Fixes #2063 for me.
* Replace any "None" strings with python None when pulling the config in the UI.
* Add 'hf_auth_token' param to api StableDiffusion class, defaulting to None, and then pass that in to the various Models where it is required and wasn't already being done before.
* Fix clip custom_weight_params being passed to export_clip_model as "external_weight_file" rather than "external_weights"
* Don't pass …
> Studio2/SD: Fix sd pipeline up to "Windows not supported"

- .gitignore
Whilst trying to remove some more blockages to Shark2 generating an image on Windows, I kept ending up with .safetensors files appearing and `git` still noticing them.
- shark2 is putting base model .safetensors files in model specific subfolders. Easiest to just ignore .safetensors completely.
> Add *.safetensors to .gitignore

- apps/shark_studio/api/sd.py
- apps/shark_studio/web/ui/sd.py
- setup_venv.ps1
On Windows, this gets us all the way to failing in iree compile of SD 2.1 base; per @monorimet this is where we expect it to fail with the current Turbine build.
You will need to `.\setup_venv.ps1 --force` to clear out the conflicting dependencies previously sourced from SRT etc.
- Fix merge errors with sd right pane config UI tab.
- Remove non-requirement.txt install/build of torch/mlir/iree/SRT in setup_venv.ps1, fixing "torch.compile not supported on Windows" error.
- Fix gradio deprecation warning for `root=` FileExplorer kwarg.
- Comment out `precision` and `max_length` kwargs being passed to unet, as not yet supported on main Turbine branch. Avoids keyword argument error.
- As usual I haven't made any changes to `./setup_venv.sh`, as I'm not currently in a position to test that. It …
> Studio2/SD/UI: Further sd ui pipeline fixes

- requirements.txt
Fixes the `AttributeError: module 'mpmath' has no attribute 'rational'` error.
> Pin mpmath version for shark 1.0

- shark/iree_utils/_common.py
After updating the .venv, `iree` started complaining that that `vulkan` was a not a valid output backend.
- Change target passed to iree for vulkan from 'vulkan' to 'vulkan-spriv', as 'vulkan' is not a valid value for --iree-hal-target-backends with the current iree compiler.
- https://github.com/openxla/iree/pull/16591 implies that using --iree-hal-target-backends is not going to be the right approach going forward, but it is what `ireec.compilestr` uses, which is what Shark is calling in turn 🤷
> Update _IREE_TARGET_MAP to return 'vulkan-spirv' for 'vulkan'

- requirements.txt
- setup_venv.ps1
Setting up a `venv` for SHARK-1.0 was getting to be a right pain, due to #2095 and there apparently no longer being any common torch version that fits both torchvision and the version of torch-mlir we have pinned for SHARK-1.0.
- Adds mpmath==1.3.0 as a direct requirement to workaround a sympy dependency issue.
- Change setup_venv.ps1 to install torchvision --nodeps. This avoids a failure to find any common torch version dependency between the pinned torch-mlir version and torchvision after a long search. This also more closely matches what setup_venv.sh does.
- Still complains about the dependency conflict around torchvision, but at least it doesn't now check every listed version of torchvision at the index url before giving up.
- Shouldn't we just `pip --freeze` everything and pin it …
> SHARK-1.0: Fixes to requirements for newer dependency versions

- shark/iree_utils/_common.py
- Change target passed to iree for vulkan from 'vulkan' to 'vulkan-spriv', as 'vulkan' is not a valid value for --iree-hal-target-backends with the current iree compiler.
> Fix _IREE_TARGET_MAP (#2103)

- README.md
Discord links for IREE were purged, so update the link on the readme.
> Update IREE discord link

- apps/shark_studio/api/initializers.py
- apps/shark_studio/api/sd.py
- apps/shark_studio/api/utils.py
- apps/shark_studio/modules/ckpt_processing.py
- apps/shark_studio/modules/pipeline.py
- apps/shark_studio/modules/shared_cmd_opts.py
- apps/shark_studio/web/ui/sd.py
- apps/shark_studio/web/utils/file_utils.py
- apps/shark_studio/web/utils/tmp_configs.py
- shark/shark_importer.py
This works fine for SD2.1 but I've noticed an issue downloading the safetensors file for clip for SD1.5. There's still some more cleanup necessary here, so I'd appreciate a second pair of eyes on it. I'm also not sure if the way I'm centralizing all the filesystem logic (just using the args and calling `os.path.join` at each usage) is the right thing to do or if we want to have everything go through, say, functions in `file_utils.py`.
> Clean up the filesystem stuff and add support for HF ckpt downloading

- .github/workflows/nightly.yml
- setup_venv.ps1
There's an IREE issue with the built exes, but not on my locally built ones. I suspect it's an IREE version issue, this is to double check that.
> Diagnose a build issue

- requirements.txt
This should fix the downstream tests for SHARK in SHARK-Turbine.
> Add a few requirements for ensured parity with turbine-models requirements.

- apps/shark_studio/modules/ckpt_processing.py
- requirements.txt
The package was renamed from `shark-turbine` to `iree.turbine` with iree-org/iree-turbine@40016ad.
> Fix installing and importing iree-turbine

- .github/workflows/gh-pages-releases.yml
- .github/workflows/nightly.yml
- .github/workflows/test-studio.yml
Pins actions to tagged versions by its hashes as suggested by the OpenSSF Scorecard project. Furthermore replaces the unmaintained `create-release` action.
> Pin, update and replace action
