shark_runner/fullyconnected.py
shark_runner/functorch_utils.py
shark_runner/iree_utils.py
shark_runner/resnet50.py
shark_runner/shark_runner.py

Added support of AOT_Module for inference on simple example.

Add support of AOT_Module in shark_runner.

---

shark_runner/fullyconnected.py
shark_runner/functorch_utils.py
shark_runner/resnet50.py
shark_runner/shark_runner.py
shark_runner/torch_mlir_utils.py

Added support for training via AOT_module in shark_runner.

Add support for training in shark_runner.

---

shark_runner/examples/fullyconnected_aot.py
shark_runner/functorch_utils.py
shark_runner/shark_runner.py

Single element is returned as is and tuple is not created for that.

Fix bug related to aot module.

---

shark_runner/examples/bert_aot.py
shark_runner/functorch_utils.py
shark_runner/shark_runner.py

Add option to attach custom inference function to aot_module.
Also, added an example of bert inference to run via aot.

Add bert aot forward example.

---

shark_runner/examples/bert_aot.py
shark_runner/examples/fullyconnected_aot.py
shark_runner/examples/hugging_face_lm_jit.py
shark_runner/examples/minilm_jit.py
shark_runner/examples/resnet50_script.py
shark_runner/examples/torch_vision_models_script.py
shark_runner/examples/unet_script.py
shark_runner/functorch_utils.py
shark_runner/iree_utils.py
shark_runner/shark_runner.py
shark_runner/torch_mlir_utils.py

This commit updates the `torch_mlir_utils.py` to use the new
torch-mlir python package structure. This commit also removes
unecessary imports from the Python scripts in the shark_runner directory.

Update torch-mlir utils + remove unecessary imports in shark_runner

---

shark/README.md

Update readme to point to the shark location.

[shark] Update readme.

---

README.md
install.sh
requirements.txt

I can't find how to maintain order in requirements.txt and
hence install.sh solves this issue.

Add necessary packages installation in install.sh.

---

.gitignore
shark/iree_utils.py

-To enable running of models and further optimization on CPU that is not x86

Automatic selection of Target Triple from Sytem clang

---

.gitmodules
inference/CMakeLists.txt
inference/README.md
inference/cmake/SharkBackendConfig.cmake.in
inference/src/dshark.cc
inference/src/libtriton_dshark.ldscript

Revert "Revert "added initial commit for libtriton backend""

---

.gitignore
setup_venv.sh

On fresh pip venv, this commit will help install
the packages onto the newly create venv.

Install package to pip venv during setup_venv

---

pytest.ini
requirements.txt
shark/examples/test_models.py
shark/shark_runner.py

Added pytests-parametrize with device and dynamic options, also
added worker flag in pytest to run tests concurrently.

Add pytests-parametrize with device and dynamic option.

---

README.md
pytest-mac.ini
shark/parser.py

-Added a separate pytest config for macos
-Adjusted shark parser to ignore unknown args

Fix Test Issues on macos

---

shark/examples/bert_training_tf.py
shark/examples/minilm_tf.py
shark/iree_utils_tf.py
shark/shark_runner_tf.py

MiniLM example sourced from iree-samples, modified to run through SHARK.

Add support for TensorFlow modules + TF miniLM example

---

.github/workflows/nightly.yml
shark/cuda_utils.py
shark/iree_utils.py

Also adds in IREE DeviceArray support for Tensorflow frontend.

Pass --iree-hal-cuda-llvm-target-arch for GPU execution automatically.

---

shark/examples/shark_eager/eager_mode.ipynb

cc @powderluv @nirvedhmeshram
link to rendered view of the notebook https://github.com/nod-ai/SHARK/blob/b8852344efec670337dd94029afbedba9d086640/shark/examples/shark_eager/eager_mode.ipynb

Eager mode ipynb

---

shark/examples/shark_eager/dynamo_demo.py

Demo for how dynamo with mlir backend can exist out of (dynamo) tree. WIP depending on what we want to show off here.
cc @powderluv

TorchDynamo demo

---

setup_venv.sh
shark/examples/shark_inference/minilm_benchmark_tf.py
shark/iree_utils.py
shark/shark_runner.py
shark/tests/test_benchmark.py

-Refactor SharkBenchmarker to run TF
-Add example and test to benchmark TF

Add benchmark for TF

---

shark/cuda_utils.py
shark/iree_utils.py
shark/model_annotation.py
shark/parser.py
shark/shark_inference.py
shark/shark_runner.py

Please use `yapf -i --style .style.yapf shark/*.py` to format python
files.

yapf format python files.

---

.github/workflows/test-models.yml
.gitignore
benchmarks/tests/test_benchmark.py
pyproject.toml
setup_venv.sh
shark/iree_utils.py
shark/shark_importer.py
shark/shark_inference.py

-Update benchmark_cl to latest benchmark_module API
-tensorflow OOM issue.

Update benchmark command to ToM and Add to test

---

shark/shark_inference.py
shark/shark_runner.py
tank/tf/README.md
tank/tf/bert_large_gen.py
tank/tf/bert_large_run.py
tank/tf/bert_large_tf.py
tank/tf/bert_small_gen.py
tank/tf/bert_small_run.py
tank/tf/bert_small_tf_run.py
tank/tf/huggingface_MiniLM_gen.py
tank/tf/huggingface_MiniLM_run.py
tank/tf/huggingface_MiniLM_tf.py
tank/tf/minilm_tf_test.py
tank/tf/seq_classification.py

on hugging face supported models.

Add seq_classification shark module to run seq_classification

---

.github/workflows/test-models.yml
shark/shark_importer.py
shark/tests/test_shark_importer.py
shark/tflite_utils.py
tank/tflite/albert_lite_base/albert_lite_base_tflite_test.py

Rewrite some tflite SharkImporter, and some code throw into tflite_utils.py
Turn on sharkimporter tests

Enable SharkImporter Tests

---

README.md
shark/iree_utils/_common.py
tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_pytorch_test.py
tank/pytorch/albert-base-v2/albert-base-v2_pytorch_test.py
tank/pytorch/bert-base-uncased/bert-base-uncased_pytorch_test.py
tank/pytorch/distilbert-base-uncased/distilbert-base-uncased_pytorch_test.py
tank/pytorch/mobilebert-uncased/mobilebert-uncased_pytorch_test.py
tank/pytorch/resnet101/resnet101_pytorch_test.py
tank/pytorch/resnet18/resnet18_pytorch_test.py
tank/pytorch/resnet50/resnet50_pytorch_test.py
tank/pytorch/wide_resnet50_2/wide_resnet50_2_pytorch_test.py

All the model validation pass except distilbert which is failing
in torch-mlir lowering. Also, added the mobilebert-uncased model to
the torch test suite.

Update pytorch tests to support vulkan and cuda.

---

README.md

I've confirmed these 5 models work on gpu and vulkan with my patches.

Update model status

---

generate_sharktank.py
shark/shark_downloader.py
shark/shark_importer.py
tank/tf/hf_masked_lm/MiniLM-L12-H384-uncased_tf_test.py
tank/tf/hf_masked_lm/albert-base-v2_tf_test.py
tank/tf/hf_masked_lm/bert-base-uncased_tf_test.py
tank/tf/hf_masked_lm/camembert-base_tf_test.py
tank/tf/hf_masked_lm/convbert-base-turkish-cased_tf_test.py
tank/tf/hf_masked_lm/deberta-base_tf_test.py
tank/tf/hf_masked_lm/distilbert-base-uncased_tf_test.py
tank/tf/hf_masked_lm/electra-small-discriminator_tf_test.py
tank/tf/hf_masked_lm/funnel-transformer_tf_test.py
tank/tf/hf_masked_lm/layoutlm-base-uncased_tf_test.py
tank/tf/hf_masked_lm/longformer-base-4096_tf_test.py
tank/tf/hf_masked_lm/mobilebert-uncased_tf_test.py
tank/tf/hf_masked_lm/mpnet-base_tf_test.py
tank/tf/hf_masked_lm/rembert_tf_test.py
tank/tf/hf_masked_lm/roberta-base_tf_test.py
tank/tf/hf_masked_lm/tapas-base_tf_test.py
tank/tf/hf_masked_lm/tiny-random-flaubert_tf_test.py
tank/tf/hf_masked_lm/xlm-roberta-base_tf_test.py
tank/tf/tf_model_list.csv

-- Tensorflow models have been imported to shark_tank.
-- TF Tests have been updated to use the downloader.

Add all the tf models to gs::shark_tank.

---

generate_sharktank.py
shark/shark_importer.py
tank/tf/automodelimageclassification.py
tank/tf/tf_model_list.csv

The model has been saved by shark tank and uploaded to google buckets.
test file in automodelimageclassfication.py

Add tf automodel image classification model

---

generate_sharktank.py
shark/shark_downloader.py

-- hash of the mlir files have been added in the shark_tank. (If there
is upstream changes, the model will be downloaded otherwise not).
-- The models have been placed in `~/.local/shark_tank/` folder as
opposed to the current folder not to redownload the files again.

Add hash of the mlir for checking upstream changes.

---

.github/workflows/test-models.yml
tank/gpu_suite.sh

No longer needed after fixes in iree

remove gpu script

---

tank/arbitrary-image-stylization-v1-256/arbitrary-image-stylization-v1-256_tflite_test.py
tank/birds_V1/birds_V1_tflite_test.py
tank/gpt2-64/gpt2-64_tflite_test.py
tank/nasnet/nasnet_tflite_test.py

- bird/arbitrary-image-stylization quantitation_info tflite fail from skip to xfail
- Fix gpt dim fail error and turn on them.
- open nasnet tests

Xfail tflite quantization_info fail on cloud

---

.github/workflows/test-models.yml
shark/iree_utils/vulkan_utils.py

Need to check the vulkan target for MacStudio

Check for MacStudio Target Value

---

tank/README.md
tank/bert_fine_tuning/bert_fine_tune_tf.py

to test, follow instructions on tank/README.md
May want to create a folder to put notebooks in instead of just floating at the top of the tank, lmk what you think.

jupyter example of fine tuning with shark

---

tank/mobilenet_v3_small_torch/mobilenet_v3_small_torch_test.py
tank/model_utils.py
tank/pytorch/torch_model_list.csv

-- The model doesn't validate with the correct results on the GPU.
-- The model passes on CPU and levelzero.
-- The static version of the model gets stuck for vulkan.

Add mobilenet_v3_small torch model to the test_suite.

---

shark/torch_mlir_utils.py

torch_mlir.compile API is updated and verified by compiling all the
torch models via generate_sharktank script.

Update torch_mlir.compile API.

---

.github/workflows/nightly.yml

prevents oom on the pytest command

split nightly pytest commands

---

.github/workflows/nightly.yml
build_tools/populate_sharktank_ci.sh
generate_sharktank.py
shark/shark_downloader.py

Adds generate sharktank to the ci, only uploads if successful.

Sharktank-ci

---

.github/workflows/test-models.yml
conftest.py
setup_venv.sh
shark/parser.py
shark/shark_benchmark_runner.py
shark/shark_downloader.py
tank/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_test.py
tank/MiniLM-L12-H384-uncased_torch/MiniLM-L12-H384-uncased_torch_test.py
tank/bert-base-uncased_tf/bert-base-uncased_tf_test.py
tank/bert-base-uncased_torch/bert-base-uncased_torch_test.py
tank/model_utils_tf.py
tank/resnet50/resnet50_test.py
tank/roberta-base_tf/roberta-base_tf_test.py
tank/xlm-roberta-base_tf/xlm-roberta-base_tf_test.py

Try:
```
IMPORTER=1 ONNX=1 ./setup_venv.sh
source shark.venv/bin/activate
pytest --benchmark --onnx_bench tank/MiniLM-L12-H384-uncased
```

Improvements to pytest benchmarks.

---

shark/examples/shark_inference/resnest.py
shark/examples/shark_inference/unet_script.py

-- Verified unet_model runs on the cpu/gpu/vulkan backend.

Update unet_model to run on shark.

---

shark/examples/shark_inference/albert_maskfill_pt.py
shark/examples/shark_inference/albert_maskfill_tf.py
shark/iree_utils/_common.py
tank/albert-base-v2_tf/albert-base-v2_tf_test.py

-Added Level Zero to common
-Added functional/fun examples to fill in sentences

Level Zero Backend

---

shark/shark_downloader.py

fix missing model download path

---

generate_sharktank.py
requirements.txt
tank/facebook_deit-small-distilled-patch16-224_torch/facebook_deit-small-distilled-patch16-224_torch_test.py
tank/google_vit-base-patch16-224_torch/google_vit-base-patch16-224_torch_test.py
tank/microsoft_beit-base-patch16-224-pt22k-ft22k_torch/microsoft_beit-base-patch16-224-pt22k-ft22k_torch.py
tank/microsoft_resnet-50_torch/microsoft_resnet-50_torch_test.py
tank/model_utils.py
tank/nvidia_mit-b0_torch/nvidia_mit-b0_torch_test.py
tank/pytorch/torch_model_list.csv

Add new torch modes:
google/vit-base-patch16-224,True,hf_img_cls,False
microsoft/resnet-50,True,hf_img_cls,False
facebook/deit-small-distilled-patch16-224,True,hf_img_cls,False
microsoft/beit-base-patch16-224-pt22k-ft22k,True,hf_img_cls,False
nvidia/mit-b0,True,hf_img_cls,False

Add torch Imageclassification automodel

---

shark/shark_downloader.py
tank/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_test.py

currently setup for tf bert/resnet50 going to refactor test class to avoid having to add an argument to 50+ files

adds support to default to tuned model

---

shark/examples/shark_inference/simple_dlrm.py

-- DLRM model is added in the shark example.
-- The model is verified on cpu, gpu and vulkan.

Add the dlrm_model in shark example.

---

shark_web/index.py
shark_web/models/albert_maskfill.py
shark_web/models/resnet50.py

This commit introduces web application for SHARK using gradio platform.
This adds web visualization of `Resnet50` and `Albert_Maskfill` models
as a start.

[WEB] Introduce web interface for the SHARK models

---

web/models/albert_maskfill.py
web/models/resnet50.py

-- Don't compile the module again and again.

[WEB] Cache the compiled module.

---

shark/examples/shark_inference/sparse_arch.py

Features that don't work with current implementation:
-- embeddingbag config with multiple features.

Add sparse architecture and test with torchrec SparseArch.

---

shark/iree_utils/_common.py
shark/iree_utils/compile_utils.py
shark/iree_utils/gpu_utils.py

Added ROCM parameters for AMD GPU

Add ROCM parameters

---

README.md
tank/test_models.py

tank/test_models.py now runs test case parameters through a filter to get rid of unintended combinations e.g. dynamic cases on models that don't support dynamic shapes.

Update README with new testing instructions and filter test cases.

---

tank/pytorch/torch_model_list.csv
tank/test_models.py

Fixes nightly failures while generating sharktank.

update xfails for PyTorch DistilBERT

---

requirements-importer-macos.txt
requirements-importer.txt
web/index.py
web/models/diffusion/v_diffusion.py

This commit removes unused parameters in the v-diffusion model. It also updated the server parameters in order to make multiple requests to be handled sequentially.

[WEB] Remove unused parameters in the v-diffuison model

---

web/README.md
web/index.py
web/models/albert_maskfill.py
web/models/diffusion/v_diffusion.py
web/models/resnet50.py
web/models/stable_diffusion.py

1. This commit adds stable-diffusion as a part of shark web.
2. The V-diffusion model has been disabled for now as it's not working(will raise a different patch with fix).
3. Add standard output in the web ui.

[WEB] Add Stable-Diffusion in the SHARK web

---

web/README.md
web/index.py

Update the location of stable-diffusion mlir file since there is some problem with iree-compile.

[WEB] Fix the mlir location of stable-diffusion model

---

.github/workflows/nightly.yml

Makes a separate job for release and publish that depends on the build.

Separate publish job

---

.github/workflows/gh-pages-releases.yml
.github/workflows/nightly.yml
setup_venv.sh
tank/test_models.py

Also: 
Fix assets path
xfail FlauBERT
Fix username in gh-pages release .yml

Update URL for IREE compiler/runtime install

---

.github/workflows/test-models.yml
tank/test_models.py

xfail tests not working
enable MacStudio Vulkan tests

Enable MacOs vulkan test on CI

---

web/index.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/model_wrappers.py

This commit exposes some parameters of the stable diffusion model in the web UI.

[WEB] Expose SD parameters in the web ui

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/iree_utils/compile_utils.py
shark/iree_utils/vulkan_utils.py

use option --iree-vulkan-target-triple= 
to set target triple for vulkan device only

add cli args for vulkan target triple

---

web/index.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/utils.py

This commit updates SD script to save the compiled module and also adds live preview of generated images.
Signed-off-by: Gaurav Shukla<gaurav@nod-labs.com>

[WEB] Save vmfb and add live preview

---

shark/examples/shark_inference/stable_diffusion/main.py

Can merge after this workflow/pip wheel is done https://github.com/nod-ai/SHARK-Runtime/actions/runs/3335140198

[example][SD] compile fp16 with iree-spirv-unify-aliased-resources

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/stable_args.py

This works in tandem with replacing the shark branch in SHARK-Runtime with https://github.com/nod-ai/SHARK-Runtime/tree/shark_alpha

Update Stable diffusion script to enable use of tuned models

---

shark/iree_utils/vulkan_utils.py

Update vulkan-target-triple for Radeon devices.

---

setup_venv.ps1

Powershell users can run ./setup_venv.ps1 to setup the env

Add setup_venv.ps1 for windows

---

shark/iree_utils/vulkan_utils.py
web/index.py
web/models/stable_diffusion/main.py

This commit enables live preview feature and also updates stable diffusion web UI.

[WEB] Update stable diffusion UI and enable live preview

---

setup_venv.ps1
web/index.py

[WEB] Add pillow dependency

---

.gitignore
web/index.py
web/models/stable_diffusion/main.py

1. Default steps = 50.
2. Live preview will yield intermediate image at every 5 steps.
3. Add logs to .gitignore

[WEB] Minor changes in the shark web

---

web/models/stable_diffusion/main.py
web/models/stable_diffusion/utils.py

This commit updates SD script in order to use the tuned version of Unet fp16 model.

[WEB] Use tuned version of UNET fp16

---

web/models/stable_diffusion/main.py

The vae and unet models(both fp16 and fp32 variant) can be loaded at server startup in order to reduce web response time.

[WEB] Load vae and unet during server start up

---

web/README.md
web/index.py
web/models/stable_diffusion/main.py
web/prompts.json

The prompt examples will now be loaded from a json file `prompts.json`.
Signed-Off-by: Gaurav Shukla

[WEB] Load prompts from json

---

shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/iree_utils/benchmark_utils.py
shark/iree_utils/compile_utils.py

To test, run:
```python main.py --precision="fp16" --device="vulkan" --iree-vulkan-target-triple=rdna2-unknown-linux --no-load_vmfb --dispatch_benchmarks="all" --dispatch_benchmarks_dir="SD_dispatches"```

Fix dispatch benchmarking tool

---

shark/examples/shark_inference/stable_diffusion/README.md
shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/stable_args.py

Update the guidance parameter argument and add the int8 version of the

---

tank/test_models.py

xfailing for CI
Shark Issue : https://github.com/nod-ai/SHARK/issues/489

xfail albert tf static cpu

---

shark/model_annotation.py

Usage:
1. Call `model_annotation` function within another python script
```
from shark.model_annotation import model_annotation
with create_context() as ctx:
module = model_annotation(ctx, input_contents=..., config_path=..., search_op=...)
```
2. Run `model_annotation.py` directly
```python model_annotation.py path_to_original_mlir path_to_config_file```

Update model annotation to take vulkan configs

---

shark/examples/shark_inference/stable_diffusion/utils.py
web/models/stable_diffusion/utils.py

Signed-off-by: Gaurav Shukla <gaurav@nod-labs.com>

Remove unnecessary torch_mlir import

---

web/index.py
web/models/stable_diffusion/main.py

[WEB] Enable guidance scale and update seed calculation

---

web/index.py
web/models/stable_diffusion/arguments.py

[WEB] Fix set_param prototype

---

web/index.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/opt_params.py

[WEB] Update seed calculation and model versions.

---

web/models/stable_diffusion/arguments.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/utils.py

[WEB] Add vulkan-heap-block-size flag

---

web/index.py

[WEB] Pressing Enter at prompt triggers Image generation

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py

Initial support for adding schedulers. This verifies the model running with the PNDM scheduler too.

Add support for different schedulers.

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/stable_args.py

Stable diffusion v2's f16 version has been added.

Add the new v2 model.

---

web/index.py
web/models/stable_diffusion/arguments.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py

[WEB] Update model wrappers and scheduler

---

web/index.py
web/models/stable_diffusion/arguments.py
web/models/stable_diffusion/main.py

[WEB] Enable Debug and disable live preview

---

shark/iree_utils/vulkan_utils.py
web/models/stable_diffusion/opt_params.py

[WEB] Update the iree flag

---

shark/examples/shark_inference/stable_diffusion/README.md
shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/iree_utils/compile_utils.py

cd ~/SHARK/shark/examples/shark_inference/stable_diffusion
python main.py --precision="fp16" --device="vulkan" --iree-vulkan-target-triple=rdna3-unknown-linux --no-load_vmfb --dispatch_benchmarks="all" --dispatch_benchmarks_dir="SD_dispatches" --dump_isa

dump all isas with amdllpc

---

shark/examples/shark_inference/stable_diffusion/opt_params.py

Update the f16-v1.4 models.

---

web/index.py

[WEB] Fix debug option and add random seed generation

---

web/models/stable_diffusion/opt_params.py

[WEB] Update to latest models.

---

shark/shark_downloader.py

[SHARK] Fix space issues in download path

---

shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py

[SHARK] Add vae encoder wrapper

---

shark/examples/shark_inference/stable_diffusion/opt_params.py

-- Enabled the clip f16 model.
-- Updated the location of sdv2 model.

Enable the clip f16 model.

---

shark/examples/shark_inference/stable_diffusion/opt_params.py

Observed correctness issues with E2E correctness when using the CLIP fp16 model.

Revert "Enable the clip f16 model." until correctness is fixed

---

shark/examples/shark_inference/stable_diffusion/stable_diffusion_amd.md

- One click installer users can reach us when they face any errors.

Move discord link from advanced instructions

---

cpp/save_img.py
requirements.txt
shark/examples/shark_inference/bloom_tank.py
shark/examples/shark_inference/minilm_jit.py
shark/examples/shark_inference/resnet50_script.py
shark/examples/shark_inference/stable_diff_f16.py
shark/examples/shark_inference/stable_diff_tf.py
shark/examples/shark_inference/stable_diffusion/utils.py
shark/examples/shark_inference/v_diffusion.py
shark/shark_downloader.py
tank/examples/bert-base-uncased_tosa_torch/bert_base_uncased_tosa.py
tank/examples/deberta-base_tf/deberta-base_tf_test.py
tank/examples/gpt2-64/gpt2-64_tflite_test.py
tank/examples/opt/opt_torch_test.py
tank/examples/rembert_tf/rembert_tf_test.py
tank/examples/tapas-base_tf/tapas-base_tf_test.py
tank/examples/v_diffusion_pytorch/cfg_sample_from_mlir.py
tank/test_models.py
web/models/resnet50.py
web/models/stable_diffusion/utils.py

Revert "find gsutil on linux"

---

cpp/save_img.py
requirements.txt
shark/examples/shark_inference/bloom_tank.py
shark/examples/shark_inference/minilm_jit.py
shark/examples/shark_inference/resnet50_script.py
shark/examples/shark_inference/stable_diff_f16.py
shark/examples/shark_inference/stable_diff_tf.py
shark/examples/shark_inference/stable_diffusion/utils.py
shark/examples/shark_inference/v_diffusion.py
shark/shark_downloader.py
tank/examples/bert-base-uncased_tosa_torch/bert_base_uncased_tosa.py
tank/examples/deberta-base_tf/deberta-base_tf_test.py
tank/examples/gpt2-64/gpt2-64_tflite_test.py
tank/examples/opt/opt_torch_test.py
tank/examples/rembert_tf/rembert_tf_test.py
tank/examples/tapas-base_tf/tapas-base_tf_test.py
tank/examples/v_diffusion_pytorch/cfg_sample_from_mlir.py
tank/test_models.py
web/models/resnet50.py
web/models/stable_diffusion/utils.py

Revert "Revert "find gsutil on linux""

---

web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py

Set the iree flags before compilation.

[WEB] Fix web performance

---

web/index.py
web/models/stable_diffusion/main.py

Generate a random seed when it's passed value is out of uint32 range.

[WEB] Fix seed when out of uint32 range

---

web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py

1. Add schedulers option in web UI.
2. Remove random seed checkbox as the same functionality can be achieved
by passing -1(or any negative number) to the seed.
Signed-Off-by: Gaurav Shukla

[WEB] Add schedulers in the web UI

---

tank/model_utils_tf.py

Initializing models globally causes TF to hang when XLA is enabled.

Initialize TF models locally

---

web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py
web/models/stable_diffusion/utils.py

[WEB] Add SD2.1 web support

---

requirements-importer-macos.txt
requirements-importer.txt
requirements.txt
setup_venv.ps1

[SHARK] Update dependencies

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/shark_importer.py

Do not merge. This will require some changes in the runtime.

Update the models to dec8

---

shark/examples/shark_inference/stable_diffusion/stable_args.py
web/index.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py
web/models/stable_diffusion/stable_args.py

1. Update the models to 8 dec.
2. precision is default to `fp16` in CLI.
3. version is default to `v2.1base` in CLI as well as web.
4. The default scheduler is set to `EulerDiscrete` now.

[WEB] Update models to 8dec and also default values

---

shark/iree_utils/_common.py
shark/iree_utils/compile_utils.py
shark/shark_downloader.py
shark/stress_test.py
shark/tests/test_stress_test.py

Adds a program to stress test the system.

Stress test program

---

.github/workflows/nightly.yml
.github/workflows/test-models.yml
.gitignore
build_tools/shark_versions.txt
conftest.py
pytest.ini
setup.py
setup_venv.sh
shark/parser.py
shark/shark_benchmark_runner.py
shark/shark_downloader.py
tank/all_models.csv
tank/test_models.py

Revert "Move most xfails to entries in tank/all_models.csv and temporarily remove multiprocessing and TF gpu support."

---

web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py

[WEB] Launch only one SD version at a time

---

.github/workflows/test-models.yml

export dyld lib path for mac CI

add vulkan lib path

---

shark/iree_utils/vulkan_utils.py

Adding support for some popular turing GPUs

Add more NVIDIA targets

---

shark/examples/shark_inference/stable_diffusion/stable_args.py
web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py
web/models/stable_diffusion/stable_args.py
web/models/stable_diffusion/utils.py

[SD][WEB] Avoid passing args to utils APIs

---

shark/examples/shark_inference/stable_diffusion/opt_params.py

Tested on Linux, but not on windows

Add VAE winograd tuned model

---

shark/examples/shark_inference/stable_diffusion/utils.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/utils.py

1. Get the correct vulkan-target-triple for a specified device in the presence of multiple cards.
2. Use tuned unet model for rdna3 cards.

[SD][WEB] Deduce vulkan-target-triple in the presence of multiple cards

---

shark/examples/shark_inference/stable_diffusion/utils.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/utils.py

Revert due to performance regression.
Reverts nod-ai/SHARK#651

Revert "[SD][WEB] Deduce vulkan-target-triple in the presence of multiple cards"

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/utils.py
shark/iree_utils/_common.py
shark/iree_utils/compile_utils.py
shark/iree_utils/vulkan_utils.py

Revert due to performance regression.
Reverts nod-ai/SHARK#529

Revert "Get appropriate target triple for specified Vulkan device"

---

web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/opt_params.py

[SD][WEB] Add vae tuned model in the SD web

---

web/models/stable_diffusion/cache_objects.py

(This goes on to produce compilation errors, but one step at a time)

Fix NoneType exception if vulkan tuning flags not detected.

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py

Combines the forward passes for each input prompt type into a single batched clip pass.

[SD] Make clip batch 2 for positive and negative prompts

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/stable_args.py

Try `--warmup_count=5` to see performance improvements.

[SD][CLI] Add a warmup phase

---

shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py

Model added to support max prompt len of 64.
precision fp16.
Untuned.

Add max prompt len 64 f16 untuned SD 

---

web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py

[SD][web] Add 64 max_length support in SD web

---

web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/stable_args.py

[SD][web] Add flag to disable the progress bar animation

---

web/index.spec
web/shark_sd.spec

[SD] Update spec files

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/utils.py
shark/iree_utils/compile_utils.py
shark/iree_utils/vulkan_utils.py

- adds functionality to autoselect vulkan target triple for a specified device for SD
- refactor get_vulkan_target_triple_flag API

Add support for automatic target triple selection (for SD)

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/resources.py
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/examples/shark_inference/stable_diffusion/utils.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/opt_params.py
web/models/stable_diffusion/stable_args.py
web/models/stable_diffusion/utils.py

At this point, all the utilities of SD web and CLI are exactly same. 
Also the `web/models/stable_diffusion/main.py` can be directly executed.

[SD] Update all the utilities to make web and CLI codebase closer

---

shark/examples/shark_inference/stable_diffusion/resources/model_db.json

add vaebase model for anythingv3 and analogdiffusion

Add vaebase for av3 and ad

---

web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py

[SD][web] Add variant support in the web UI

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/resources/model_db.json

- Adds Open Journey (SD fine tuned on MidJourney images!) 
- also corrects error class for variant not found error

Add Open Journey

---

web/index.py
web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/stable_args.py
web/models/stable_diffusion/utils.py

1. Now device selection is available through UI.
2. Models reloading will only happen when there will be a change in the settings(variant + device).

[SD][web] Add device support in the SD web UI

---

shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/utils.py
web/models/stable_diffusion/opt_params.py
web/models/stable_diffusion/utils.py

[SD] Fix flags for cuda devices

---

shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/resources/model_db.json
shark/examples/shark_inference/stable_diffusion/utils.py

- add support for dreamlike diffusion (use `--variant=dreamlike`)
- precision fp32 fp16
- prompt max length - 77

Add support for dreamlike diffusion

---

shark/examples/shark_inference/stable_diffusion/utils.py
web/index.py
web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/resources/model_db.json
web/models/stable_diffusion/utils.py

[SD][web] Add openjourney and dreamlike in SD web UI

---

web/index.py
web/models/stable_diffusion/stable_args.py

[SD][web] Add flags for global URL and server port

---

web/models/stable_diffusion/model_wrappers.py
web/models/stable_diffusion/opt_params.py
web/models/stable_diffusion/resources.py
web/models/stable_diffusion/resources/model_config.json

This cleans model_wrappers.py file.

[SD][web] Add a json file for model configuration

---

requirements-importer.txt
shark/shark_benchmark_runner.py

Test run: https://storage.googleapis.com/shark-benchmark-artifacts/2023-01-10.sha_0b4a.timestamp_1673321650.manual/summary.html

Enable Torch Inductor

---

web/shark_sd.spec

[SD] Update spec file to include model_config.json

---

web/models/stable_diffusion/cache_objects.py
web/models/stable_diffusion/utils.py

[SD][web] Fix device key error

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/stable_args.py

- adds json info for each generated image with the same name as the image file
- changes images name to take partial prompt, seed and date time.
- gives option to save images in a specified dir using `--output_dir` flag

add json data for each image

---

shark/shark_benchmark_runner.py

This was a local change that didn't make it into https://github.com/nod-ai/SHARK/pull/784

Enable Torch-Inductor Part 2

---

web/models/stable_diffusion/main.py
web/models/stable_diffusion/stable_args.py

[SD][web] Add support for saving generated images

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/sd_annotation.py
web/models/stable_diffusion/main.py

Increased to JPEG95 from the default JPEG75 which is way too compressed. Output image size is now ~100-200kb. Previously was ~20kb.

Increase JPEG output quality & disable subsampling

---

web/demo.css
web/index.py

Fixes [issues/807](https://github.com/nod-ai/SHARK/issues/807) 
Extracts webUI custom css into separate file. 
Passes file path to gr.Blocks as css parameter

fix: :bug: Extract demo css string to css file

---

web/index.py
web/models/stable_diffusion/main.py

This also moves the location of `imgs_history.csv` to `generated_imgs` directory.

[SD][web] Add a UI textbox to show the output location

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/utils.py
web/models/stable_diffusion/main.py
web/models/stable_diffusion/utils.py

- add disk space warning (<20GB) before loading / compiling
- add disk space warning (<5GB) before saving images

remaining disk space warning

---

shark/examples/shark_inference/stable_diffusion/README.md
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/resources.py
shark/examples/shark_inference/stable_diffusion/resources/model_config.json
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/examples/shark_inference/stable_diffusion/utils.py

-- This commit adds CKPT support to update models irrespective of `import_mlir` flag.

[SD-CLI] Add CKPT support to update models irrespective of `import_mir` flag

---

shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/utils.py

-- This commit makes `custom_model` take highest priority for generating models if present.

[SD-CLI] Make `custom_model` take highest priority for generating model if present

---

shark/examples/shark_inference/stable_diffusion/main.py
web/models/stable_diffusion/main.py

default remains png, jpeg just is set to be optimized and progressive so it loads better and is a little more compressed without any quality decrease.

make jpeg optimized and progressive

---

shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/resources.py
shark/examples/shark_inference/stable_diffusion/resources/base_model.json
shark/examples/shark_inference/stable_diffusion/resources/opt_flags.json
shark/examples/shark_inference/stable_diffusion/resources/variants.json
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/examples/shark_inference/stable_diffusion/utils.py

The custom models shouldn't depend on shark_tank in anyway.

Refactor shark_tank models and custom models.

---

shark/examples/shark_inference/stable_diffusion/model_wrappers.py

This commit fixes args.max_length range check.

[SD-CLI] Fix args.max_length range check

---

shark/examples/shark_inference/stable_diffusion/README.md
shark/examples/shark_inference/stable_diffusion/main.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/resources/variants.json
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/examples/shark_inference/stable_diffusion/utils.py

This PR includes 2 commits :-
1. The first one is a fix in `variants.json` file's mapping.
2. The second one makes using custom weights easier for end users.

[SD-CLI] Make using custom weights easier + fix a mapping in variants.json

---

shark/examples/shark_inference/stable_diffusion/main.py

Reverts nod-ai/SHARK#848. Not really a fix.

Revert "potential fix to pre-load DLL dir for torch-mlir"

---

shark/examples/shark_inference/stable_diffusion/README.md
shark/examples/shark_inference/stable_diffusion/resources/variants.json
shark/examples/shark_inference/stable_diffusion/utils.py

-- This commit fixes CKPT script to rely on the previous CKPT to Diffusers
script.
TODO: Let go of the script once the CKPT is included in next release
of diffusers.
-- It also adds many variants as part of `variants.json`.

[SD-CLI] Fix CKPT script + add more variants

---

shark/examples/shark_inference/stable_diffusion/main.py

Remove the dependency of torchvision library for the conversion of tensor layout format to what PIL library expects.

Remove the dependency of the torchvision.

---

dataset/README.md
dataset/annotation_tool.py
dataset/args.py
dataset/utils.py

- add args usage, pass gs_url by CL flag
- add support for no existing prompts

Address TODOs for dataset annotator

---

shark/examples/shark_inference/stable_diffusion/main.py
web/index.py

Add an option to respect LLPC env var

---

shark/examples/shark_inference/stable_diffusion/main.py

- update correct seed value in file name and json

fix seed values in SD json and filename

---

shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/utils.py

-- This commit cleans up vmfb files generated as a result of retry method.

[SD-CLI] Clean up vmfbs if a retry method fails

---

build_tools/stable_diff_main_test.sh
generate_sharktank.py
shark/examples/shark_inference/stable_diffusion/model_wrappers.py
shark/examples/shark_inference/stable_diffusion/opt_params.py
shark/examples/shark_inference/stable_diffusion/resources.py
shark/examples/shark_inference/stable_diffusion/resources/beta_model_db.json
shark/examples/shark_inference/stable_diffusion/stable_args.py
shark/examples/shark_inference/stable_diffusion/utils.py
shark/shark_importer.py

Currently supports 2_1_base models.

add generate_sharktank for stable_diffusion model defaults

---

shark/iree_utils/compile_utils.py

Fixed a bug that would cause shark to say level_zero is unsupported when trying to specify which gpu to use
Also removed code that had been commented out

fixed a bug that would sometimes cause intel-gpu to appear unsupported

---

apps/stable_diffusion/scripts/__init__.py
apps/stable_diffusion/shark_sd.spec
apps/stable_diffusion/shark_sd_cli.spec
apps/stable_diffusion/src/__init__.py
apps/stable_diffusion/src/models/__init__.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/models/opt_params.py
apps/stable_diffusion/src/pipelines/__init__.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/schedulers/__init__.py
apps/stable_diffusion/src/schedulers/sd_schedulers.py
apps/stable_diffusion/src/schedulers/shark_eulerdiscrete.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/profiler.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
setup.py
web/models/stable_diffusion/main.py

Build with pyinstaller.exe .\apps\stable_diffusion\web\shark_sd.spec
normal flow works. exe is missing a few json files

Add PyInstaller for apps/

---

.gitignore
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/models/__init__.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/models/opt_params.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/resources/opt_flags.json
apps/stable_diffusion/src/utils/sd_annotation.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py

-- This commit fixes a few bugs in `apps`'s SD CLI and brings it
up to speed with SD CLI.

[APPS-SD] Fix a few bugs and bring it up to speed with SD CLI

---

apps/stable_diffusion/scripts/txt2img.py

[SD] Fix output image location

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/utils.py

-- This commit prepones loading of vmfbs, if present, for all sub-models.
-- It also involves restructuring the SD pipeline to achieve the loading
of vmfbs smoothly and postpones processing of checkpoint files only when
required.
-- It also fixes a bug in Sharkify SD API.

[apps-SD] Prepone loading of vmfbs + restructure the SD pipeline + bug fix

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/index.py

[SD] Merge model id dropdown and .ckpt dropdown

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/utils.py

* Bring back the --runs=x option for command line users.
* Fix issue https://github.com/nod-ai/SHARK/issues/942 (csv included)
Proposed as draft:
* I didn't noticed a problem, but more testing should be done.
* I'm not a Python expert, it would be nice to have a little feedback from a more experienced guy, just in case.
Thanks.

Add --runs options to the cmd command and fix wrong infos in csv, json and png

---

apps/stable_diffusion/shark_sd.spec

exe should now default to dark theme too

Add css in exe

---

.gitignore
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/resources.py

-- This commit fixes the session restart error for SD.
-- It also overrides `args.use_tuned` for `import_mlir`, and sets `use_tuned` as `False`.

Fix restart SD session error + override args.use_tuned temporarily

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/web/index.py

[SD] Add batch count in stable diffusion

---

.gitignore
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/resources.py
apps/stable_diffusion/src/utils/utils.py

-- This commit fixes SD restart error in exe file by creating variants.json in CWD instead of a relative path.

Fix SD restart error in exe file

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/src/__init__.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/__init__.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py

- Adds img2img support for cli 
- command `python apps/stable_diffusion/scripts/img2img.py --prompt=<prompt text> --img_path=<input img path> --import_mlir --no-load_vmfb --hf_model="stabilityai/stable-diffusion-2-1-base" --clear_all `

add support for img2img

---

apps/stable_diffusion/scripts/__init__.py
apps/stable_diffusion/scripts/img2img.py

[SD] Fix parameters in img2img

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/web/ui/img2img_ui.py

It works with some local changes in shark-runtime. Will have this feature soon.

[SD] Fix input image type

---

apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/txt2img_ui.py

This is a rework of https://github.com/nod-ai/SHARK/pull/982 updated for the new tabbed interface.
This is pretty much the same, except hf_model_id is left untouched.

Add support for command arguments to the WebUi

---

apps/stable_diffusion/src/utils/resources/opt_flags.json

Drop im2col for VAE since it crashes the driver

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/shark_sd.spec
apps/stable_diffusion/web/index.py

Remove forcing LLPC setting

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
apps/stable_diffusion/src/utils/stable_args.py

- add strength param to img2img
use: `python apps/stable_diffusion/scripts/img2img.py --prompt=<prompt text> --img_path=<input image> --import_mlir --no-load_vmfb --hf_model="stabilityai/stable-diffusion-2-1-base" --clear_all --enable_stack_trace --scheduler=PNDM --strength=0.8`
- fix size issue

add strength param

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/__init__.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/index.py
apps/stable_diffusion/web/ui/img2img_ui.py

1. Update iree_vulkan_target_triple when device is switched.
2. Add batch count in img2img web.
3. Move `save_output_img` and `clear_all` to utility.

[SD] Update iree_vulkan_target_triple when device is switched

---

apps/stable_diffusion/src/models/model_wrappers.py

-- This commit adds support for standalone Vae checkpoints.

[SD] Add support for standalone Vae checkpoints

---

requirements.txt

Get rid of the wget problem we had

Pin to latest diffusers

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py

- fix strength param to work with lower values of strength

img2img denoise strength

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/txt2img.py

[SD] Reset args.img_path to None in txt2img to avoid vae_encode

---

requirements.txt

unpin diffuser to latest

---

apps/stable_diffusion/web/ui/css/sd_dark_theme.css

Gradio was updated to v3.19.0 few hours ago.
Here is the css fix.

[WebUi] css fix for Gradio v3.19.0

---

apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/src/__init__.py
apps/stable_diffusion/src/pipelines/__init__.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/stable_args.py
shark/examples/shark_inference/sharded_bloom.py

Add outpainting support on CLI
Flags:
--pixels: Number of pixels to be expanded (min=8, max=256, step=8)
--mask_blur: Number of blur pixels (min=0, max=64, step=1)
--left, --right, --top, --bottom: Expanding directions
`python apps/stable_diffusion/scripts/outpaint.py --prompt="your prompt" --img_path=path/to/img --import_mlir --hf_model_id="stabilityai/stable-diffusion-2-inpainting" --pixels=128 --mask_blur=8 --left --right --top --bottom --steps=20`

Add SD outpainting

---

apps/stable_diffusion/scripts/__init__.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/index.py
apps/stable_diffusion/web/ui/__init__.py
apps/stable_diffusion/web/ui/outpaint_ui.py

- add outpainting support on web UI
- add flags --noise_q, --color_variation for outpainting

Add outpainting web UI

---

apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_inpaint.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/schedulers/sd_schedulers.py

Issue : #1076
Added DEISMultistepScheduler from huggingface

Add DEISMultistep scheduler #1076

---

apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/utils/stable_args.py

Doesn't work for f16 and needs changes that aren't in upstream torch-mlir yet.

Add attention slicing support

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/stencils/canny/__init__.py
apps/stable_diffusion/src/utils/stencils/stencil_utils.py

-- This commit adds ControlNet execution to img2img.
-- It restructures the addition of ControlNet variants.
-- It also fixes scheduler selecting bug for img2img pipeline.
NOTE: I'm already working on adding this to WebUI as well.

[SD] Add ControlNet to img2img + fix bug for img2img scheduler

---

apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/utils/resources/base_model.json

-- add compiling shark modules

add shark models for stencilSD

---

requirements.txt

Revert "Update diffusers"

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/inpaint_ui.py
apps/stable_diffusion/web/ui/outpaint_ui.py

This PR includes
- Update metadata info for img2img and inpaint.
- Make canvas(input image to be masked) a bit bigger in case of inpaint.
- Update output gallery for each inference in case of more than one batch count.

[SD] Update metadata info and canvas size

---

requirements.txt

-- install diffusers from nod's SHARK branch
-- add cv2 ( => opencv-python ) installation for StencilNet

add cv2 and nod diffusers

---

requirements.txt

Revert "add cv2 and nod diffusers"

---

apps/stable_diffusion/src/models/model_wrappers.py
requirements.txt

-- txt2img expects only 3 mlirs
-- add venv requirements for stencils

remove extra return arg

---

shark/examples/shark_training/stable_diffusion/README.md
shark/examples/shark_training/stable_diffusion/stable_diffusion_fine_tuning.py

This commit adds the sd fine tuning script which runs through the torchdynamo path.

Add Stable diffusion fine tuning script

---

apps/stable_diffusion/src/utils/utils.py

Include only the driver name instead.

In SD don't include device path in vmfb filename

---

cpp/README.md
shark/iree_utils/compile_utils.py
shark/iree_utils/cpu_utils.py
tank/examples/MiniLM_tf/huggingface_MiniLM_run.py
tank/examples/bert_fine_tuning/bert_fine_tune_tf.py
tank/examples/bert_tf/bert_large_run.py
tank/examples/bert_tf/bert_small_run.py

This changes the flags to reflect the change in iree-compile.

Update iree-compile flags --iree-llvm-xxx -> --iree-llvmcpu-xxx

---

requirements.txt

https://discord.com/channels/973663919757492264/975522729564446740/1085109774758191164

workaround Gradio issue

---

.gitignore
apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/shark_sd.spec
apps/stable_diffusion/shark_sd_cli.spec
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/stencils/__init__.py
apps/stable_diffusion/src/utils/stencils/openpose/__init__.py
apps/stable_diffusion/src/utils/stencils/openpose/body.py
apps/stable_diffusion/src/utils/stencils/openpose/hand.py
apps/stable_diffusion/src/utils/stencils/openpose/openpose_util.py
apps/stable_diffusion/src/utils/stencils/stencil_utils.py
apps/stable_diffusion/web/ui/img2img_ui.py
process_skipfiles.py
requirements.txt

-- This commit adds openpose model variant to stencil.

[SD] Add Openpose to Stencil

---

apps/stable_diffusion/src/utils/stable_args.py
shark/iree_utils/_common.py

based on hf_model_id. Works on windows

Add IREE_SAVE_TEMPS for import_debug command

---

apps/stable_diffusion/shark_sd.spec

add missing import for shark_sd.spec

---

apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/stencils/stencil_utils.py
apps/stable_diffusion/web/ui/img2img_ui.py
process_skipfiles.py
requirements.txt

This PR consists of 2 commits :-
Commit 1 - Provides fix for using latest diffusers.
Commit 2 - Adds scribble variant to Stencil.

[SD] Add fix for using latest diffusers + add scribble variant to Stencil

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/ui/txt2img_ui.py

-- This commit adds LoRA inference to SD pipeline.
-- It also modifies txt2img to incorporate the new feature.
img2img, inpaint, outpaint, etc using Unet can also be extended in a
similar way.

[SD] Add LoRA inference to SD pipeline

---

apps/stable_diffusion/scripts/upscaler.py
apps/stable_diffusion/web/ui/upscaler_ui.py

Add support for upscaling large size images by partitioning it to 128x128 tiles.

[SD] Add support for larger size upscaling

---

shark/shark_importer.py

Fixes the compilation issue for fp16 attention slicing for Stable Diffusion.

Add fix for attention slicing fp16

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/scripts/upscaler.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/sd_annotation.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/css/sd_dark_theme.css
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/inpaint_ui.py
apps/stable_diffusion/web/ui/outpaint_ui.py
apps/stable_diffusion/web/ui/txt2img_ui.py
apps/stable_diffusion/web/ui/upscaler_ui.py
apps/stable_diffusion/web/ui/utils.py
requirements.txt

This PR contains 3 commits :-
Commit 1
-- Updates LoRA inference to handle various checkpoints.
-- It also updates `requirements.txt` to point to upstream un-released
`diffusers`.
Commit 2
-- Updates WebUI utilities to support LoRA inference.
Commit 3
-- Fix a bug pertaining to sd_annotation.py.
-- Get rid of the X button in LoRA's dropdown.

[SD] Update LoRA inference to handle various checkpoints

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/scripts/upscaler.py
apps/stable_diffusion/web/index.py
process_skipfiles.py

-- This commit fixes the transformers/__init__.py issue in PyInstaller.

[SD] Fix for transformers/__init__.py issue in PyInstaller

---

build_tools/stable_diffusion_testing.py

(more accurately, xfail them for now)

fix false positives

---

shark/iree_utils/vulkan_target_env_utils.py
shark/iree_utils/vulkan_utils.py

This just enables the plumbing. It generates black images.

Add Intel ARC A770 target triple

---

apps/stable_diffusion/scripts/img2img.py
apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/scripts/upscaler.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_inpaint.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_outpaint.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_upscaler.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/inpaint_ui.py
apps/stable_diffusion/web/ui/outpaint_ui.py
apps/stable_diffusion/web/ui/txt2img_ui.py
apps/stable_diffusion/web/ui/upscaler_ui.py

#1203 
- check "Low VRAM" checkbox on webui or use --ondemand flag on cli
- TODO: unload clip

Load and unload SD models on demand

---

apps/stable_diffusion/src/models/model_wrappers.py

- fixes size mismatch error for upscalar vae

Add fix for vae fp32 Upscalar

---

apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/upscaler.py
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/txt2img_ui.py
apps/stable_diffusion/web/ui/utils.py
apps/stable_diffusion/web/utils/global_obj.py

- add ondemand back to img2img
- workaround memory leak for batch count

Fix low vram mode issues

---

shark/iree_utils/vulkan_utils.py

Add AMD W7900 target triple

---

apps/stable_diffusion/scripts/inpaint.py
apps/stable_diffusion/scripts/outpaint.py
apps/stable_diffusion/scripts/upscaler.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/schedulers/shark_eulerdiscrete.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/txt2img_ui.py

support ondemand for outpainting and multi batch_count

Fix memory leak with ondemand

---

apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/utils/stencils/stencil_utils.py
apps/stable_diffusion/web/ui/img2img_ui.py

-- This commit addresses the following :-
1. Adapts SHARK's v1 img2img API to work with SdPaint.
2. Updates Stencil's HF model ID to a newer/better version.
3. Updates the vmfb naming to help compile only Stencil's Adaptor.

[SD] Adapted SHARK's v1 img2img API for SdPaint + updated Stencil model ID

---

apps/stable_diffusion/web/index.py
apps/stable_diffusion/web/ui/__init__.py
apps/stable_diffusion/web/ui/chatbot_ui.py

-- This commit includes FastChat as part of SD WebUI.
For this to work we need https://github.com/nod-ai/FastChat/pull/1 (Merged).

[SD] Add FastChat as part of SD WebUI

---

apps/stable_diffusion/web/index.py
apps/stable_diffusion/web/ui/__init__.py
apps/stable_diffusion/web/ui/chatbot_ui.py

Revert "[SD] Add FastChat as part of SD WebUI"

---

apps/stable_diffusion/shark_sd.spec
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/index.py
requirements.txt

Default behavior is now "app". linux users may experience extra hurdles

add tkinter launch for webui

---

shark/examples/shark_inference/standalone_vicuna.py

added script for standalone vicuna that produces text generation

added standalone vicuna script

---

shark/model_annotation.py

Matches https://github.com/nod-ai/SHARK-Runtime/pull/58

Revert dialect registration in model annotator

---

apps/language_models/scripts/sharded_vicuna_fp32.py

- vulkan
- short context / history of conversation
- fp32

vicuna chat CLI

---

requirements.txt

Signed-Off-by: Gaurav Shukla <gaurav@nod-labs.com

[SD] Fix gradio to 3.22.0 version

---

apps/language_models/scripts/vicuna.py

- displays tokens as soon as generated to ensure there is some output for the user to see
- extra spaces and other special characters need to handled in upcoming changes

add continuous output for CLI

---

apps/language_models/scripts/stablelm.py
apps/stable_diffusion/web/ui/stablelm_ui.py

- gets stablelm to generate output all at once, not tokenwise
- tokenwise output can be seen on the console during generation
- err outputs need fixing

fix #2 SLM in SharkStudio

---

apps/language_models/scripts/stablelm.py
apps/stable_diffusion/web/ui/stablelm_ui.py

- device arg extracted out in script for easy change of device
- cleanup ui script
- next add device change from UI
- next add precision change arg

SLM on Sharkstudio

---

apps/language_models/scripts/stablelm.py
apps/language_models/scripts/vicuna.py
apps/language_models/utils.py
apps/stable_diffusion/web/ui/stablelm_ui.py

- Refactor compile API for LLMs to create base for LLM pipeline

LLM refactor #1

---

tank/torch_model_list.csv

To fix https://github.com/nod-ai/SHARK/issues/1441

Add GPT3/OPT to Stablehlo in shark tank

---

tank/torch_model_list.csv

https://github.com/nod-ai/SHARK/issues/1440

Add distilgpt2 to stablehlo in shark tank

---

apps/stable_diffusion/src/utils/sd_annotation.py
apps/stable_diffusion/src/utils/utils.py

New 512x512 and 768x768 unet tunings (768 speeds up a little with this config but not by much. Tuning was disabled for 768^2 on rdna2 previously.)

Replace RDNA2 SD2.1 Unet lowering configs.

---

apps/stable_diffusion/web/index.py

Was able to test inpainting, upscaling and various sizes on my macos machine.

fix osx torch_mlir

---

apps/language_models/src/pipelines/vicuna_pipeline.py
shark/iree_utils/_common.py

- expose local-task and local-sync as cpu devices

Cpu device map

---

apps/language_models/src/model_wrappers/vicuna_model.py
shark/shark_generate_model_config.py

Model config generator takes a PyTorch model as input and generates a JSON file with model layers and other propperties that define sharding on a particular hardware.

Add a model config generator

---

shark/shark_importer.py
tank/torch_model_list.csv

shark_tank/chi-nod/deberta/microsoft_deberta-v3-base_torch_BS1
https://storage.googleapis.com/shark_tank/chi-nod/deberta/microsoft_deberta-v3-base_torch_BS1/microsoft_deberta-v3-base_torch_stablehlo.mlir

Add Deberta to stablehlo in shark tank

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/txt2img_ui.py
shark/iree_utils/vulkan_target_env_utils.py
shark/iree_utils/vulkan_utils.py
shark/shark_importer.py
tank/torch_model_list.csv

The frontend work still needs some cleanup I think, and I need to check if it's truncating the prompts still, but otherwise I think this is good to go.

Add UNet512

---

apps/stable_diffusion/web/index.py

This is to ensure pyinstaller picks it up

Add PIL in main index.py

---

mega_test.py

-- Usage: `python mega_test.py`.

[MEGABYTE] Add script to compile MEGABYTE through SHARK

---

apps/stable_diffusion/src/utils/sd_annotation.py
apps/stable_diffusion/src/utils/utils.py

Changed files: utils.py and sd_annotation.py to allow for use of the tunings generated. Previously passing in arguments with dimesions of 512x768 or 768x512 would set variable use_tuner to false, which wouldn't use the tunings created. I changed that as well as changed the syntax for searching in the cloud to fit the naming convention used on the files.

changes for tuning

---

apps/language_models/src/pipelines/vicuna_sharded_pipeline.py

The Vicuna class wasn't passing device variable, now sharded vicuna should use the designated device

fixed a bug where designating device for vicuna didn't work

---

apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/stablelm_ui.py
requirements.txt

- show cpu name for devices instead of default

cpu name in device

---

apps/language_models/scripts/vicuna.py
apps/stable_diffusion/web/ui/stablelm_ui.py
requirements.txt

- adds vicuna v1.3 and codegen2.5 to WebUI

Add Vicuna V1.3 and CodeGen2.5 models

---

apps/language_models/scripts/vicuna.py

- tested it unpacks int4 as expected
- tested it doesn't make difference on int8

Apply canonicalize for unpacking int4

---

requirements.txt

Used in https://github.com/nod-ai/SHARK/pull/1657 but not included in requirements.txt

Fixed Joblib Import Error

---

tank/examples/opt/opt_perf_comparison.py

- fix padding for HF + pytorch runtime
- don't benchmark tokenizers

small changes to opt_perf_comparison.py

---

setup.py
setup_venv.ps1
setup_venv.sh

Torch MLIR should not require pinning after this lands: https://github.com/llvm/torch-mlir/pull/2321

Unpin Torch MLIR

---

apps/language_models/README.md
apps/language_models/scripts/vicuna.py

- add fix to make web and api working

Add ReadMe for CodeGen Setup

---

apps/language_models/scripts/vicuna.py
apps/stable_diffusion/web/ui/stablelm_ui.py

Revert "Add Llama2 70B option in CLI and WebUI"

---

apps/language_models/scripts/vicuna.py
apps/language_models/src/model_wrappers/vicuna_model.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/ui/stablelm_ui.py

I have tested the patch for all the paths, and it works fine.

Add support for Llama-2-70b for web and cli, and for hf_auth_token

---

apps/language_models/langchain/gen.py
apps/language_models/langchain/h2oai_pipeline.py
apps/stable_diffusion/web/ui/h2ogpt.py

Authored-by: George Petterson @gpetters94

Fix Langchain Prompt issue and add web UI support

---

apps/language_models/langchain/cli.py
apps/language_models/langchain/eval.py
apps/language_models/langchain/gen.py
apps/language_models/langchain/gpt_langchain.py
apps/language_models/langchain/h2oai_pipeline.py
apps/stable_diffusion/web/ui/h2ogpt.py

This commit fixes the following issue for the Langchain:
1.) Web UI not able to fetch results.
2.) For each query model getting reloaded.
3.) SHARK module not using user-provided device and precision.
4.) Create a class for main Langchain code.
5.) Misc issues

Fix multiple issue for Langchain

---

apps/language_models/scripts/vicuna.py
shark/shark_importer.py

Fix and reformat vicuna script

---

apps/stable_diffusion/src/utils/profiler.py
apps/stable_diffusion/src/utils/utils.py

- fixes SD working with cpu
- SD on CPU is slow but functional

fix SharkStudio SD CPU 

---

apps/stable_diffusion/scripts/train_lora_word.py
apps/stable_diffusion/shark_studio_imports.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/index.py
apps/stable_diffusion/web/ui/__init__.py
requirements.txt

temporarily disable langchain stuff in webui

---

apps/stable_diffusion/src/utils/stable_args.py

Tested and works well. (modulo unrelated driver issue)

re-enable constant folding

---

apps/language_models/scripts/vicuna.py

- change assignment of global constants to first / second llama acc to their use in respective methods.

fix combine mlir for llama2

---

apps/language_models/scripts/vicuna.py

replace public with private

---

tank/examples/opt/README.md
tank/examples/opt/opt_perf_comparison.py
tank/examples/opt/opt_perf_comparison_batch.py

Add a short README for the OPT examples and small tweaks.

---

apps/language_models/scripts/stablelm.py
apps/language_models/scripts/vicuna.py
apps/language_models/src/pipelines/SharkLLMBase.py
apps/language_models/src/pipelines/falcon_pipeline.py
apps/language_models/src/pipelines/minigpt4_pipeline.py
apps/language_models/src/pipelines/stablelm_pipeline.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
shark/iree_utils/compile_utils.py
shark/shark_inference.py
tank/examples/opt/opt_causallm.py

This might seem a little heavy-handed but I've wanted to have an option piped down for things like this anyways.

Pipe through a debug option to iree compile utils.

---

apps/language_models/langchain/h2oai_pipeline.py
apps/language_models/scripts/vicuna.py
apps/language_models/src/pipelines/minigpt4_pipeline.py
shark/shark_compile.py

update passes based on https://github.com/llvm/torch-mlir/pull/2402

Update conversion passes for brevitas quant op

---

process_skipfiles.py

Keeps a small typo fix but reverts the rest of changes to this file from https://github.com/nod-ai/SHARK/commit/450c231171f0b56620f94e0f883d828fd2fb2917

Fix process_skipfiles.py

---

apps/language_models/scripts/vicuna.py
apps/language_models/src/model_wrappers/vicuna_model.py

This is primarily @PhaneeshB's work, just prepping it to merge into main

Llama2 70b

---

shark/iree_utils/compile_utils.py
shark/shark_importer.py
tank/test_models.py

-- This commit adds Scaled Dot Product Flash Attention's decomposition
in shark_importer.

[SD] Add sdpfa decomposition

---

apps/language_models/scripts/vicuna.py
apps/stable_diffusion/web/ui/stablelm_ui.py

- modifies role tokens as per format expected by llama2 to get more meaningful results.

add roles for llama2

---

apps/stable_diffusion/src/utils/utils.py

local_tank_cache included into clear_all

---

apps/language_models/scripts/vicuna.py

The past key values are only used within the models themselves and can be kept on device. For vulkan int4, this gives 44 tok/s (for the first prompt) and settles at around 26 tok/s on 7900xtx.

[vicuna.py] Keep past key values on device

---

shark/iree_utils/vulkan_target_env_utils.py

Update vulkan target env script that hardcodes related attributes.

[vulkan] Switch from coop matrix NV to KHR

---

apps/stable_diffusion/src/utils/utils.py
shark/iree_utils/vulkan_utils.py

- fix to remove use of vulkaninfo to get vulkan device list

remove use of vulkaninfo

---

apps/stable_diffusion/scripts/txt2img.py
apps/stable_diffusion/src/__init__.py
apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/models/opt_params.py
apps/stable_diffusion/src/pipelines/__init__.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_txt2img_sdxl.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py
apps/stable_diffusion/src/utils/resources/base_model.json
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/ui/txt2img_ui.py

-- This commit adds SDXL pipeline to SHARK.

[SDXL] Add SDXL pipeline to SHARK

---

tank/examples/opt/opt_causallm.py
tank/examples/opt/opt_causallm_samples.py
tank/examples/opt/opt_perf_comparison.py
tank/examples/opt/opt_util.py

- Add opt_causallm_samples.py that run opt_causallm.generate_tokens() with the sample prompts.
- Separate out the sample prompts from opt_perf_comparison.py to opt_util.py for reuse.

Add opt_causallm_samples.py.

---

apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/ui/stablelm_ui.py
shark/iree_utils/_common.py
shark/iree_utils/compile_utils.py
shark/iree_utils/gpu_utils.py

- temp fix to pass rocm device architecture using `--iree_rocm_target_chip=<arch>`

update dependency on rocm/hip info command

---

benchmarks/tests/test_benchmark.py
shark/iree_utils/_common.py
tank/examples/deberta-base_tf/deberta-base_tf_test.py
tank/examples/opt/opt_causallm.py
tank/examples/rembert_tf/rembert_tf_test.py
tank/examples/tapas-base_tf/tapas-base_tf_test.py

- Uses the `iree.runtime.get_driver` to check for the existence of driver
- removes unused imports and call fixes

Use iree tools to get supported driver info

---

apps/language_models/src/model_wrappers/falcon_sharded_model.py
apps/language_models/src/pipelines/falcon_pipeline.py

This commit adds the support for sharded Falcon-7b-GPTQ and Falcon-180B-GPTQ. This commit also adds the support for 4-way sharding of the Falcon model for the device ROCM.
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

Add sharded Falcon-GPTQ support

---

apps/language_models/scripts/vicuna.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/ui/stablelm_ui.py
shark/iree_utils/compile_utils.py
shark/iree_utils/gpu_utils.py

- support for choosing different rocm devices from web and cli
- expected device format `rocm://<index>` support to select device as `rocm://<uri_path>` will be added later.

Update rocm device selection logic

---

.github/workflows/test-models.yml
apps/stable_diffusion/src/utils/stable_args.py
build_tools/stable_diffusion_testing.py
shark/model_annotation.py

This reverts commit 70817bb50ab9b9205733607955cc25f7abefc4da.
With latest SRT versions, SD tunings break again completely. Disable them by default.

Disable tunings and fix CI vulkan driver issues.

---

apps/language_models/scripts/vicuna.py

This makes the program wait for tracy profiler to connect before exiting and flush profiling data after each token.
I don't know how to select the tracy iree-runtime variant programatically -- instead, print an error and exit.

[vicuna.py] Add option to enable tracing

---

requirements-importer.txt

Fix for a small problem that's been breaking the venv on my system.

Fix an importer issue on Linux

---

.github/workflows/test-models.yml
apps/stable_diffusion/src/utils/resources/opt_flags.json
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/src/utils/utils.py
shark/iree_utils/compile_utils.py

https://github.com/openxla/iree/commit/c5a6cdc8dd89b048b81e212f7ca674aa111d56f1
https://github.com/openxla/iree/commit/52eb7e9b82380500a9776a1dbe2d26ae093b0191
tweak CPU iree-compile flags to match upstream changes.

Update default CPU compilation flags.

---

apps/stable_diffusion/src/schedulers/__init__.py
apps/stable_diffusion/src/schedulers/sd_schedulers.py
apps/stable_diffusion/src/utils/stable_args.py
apps/stable_diffusion/web/index.py
apps/stable_diffusion/web/ui/stablelm_ui.py
apps/stable_diffusion/web/ui/txt2img_sdxl_ui.py
apps/stable_diffusion/web/ui/utils.py
shark/iree_utils/compile_utils.py

Fixes to llama2 cpu compilation (turns off data tiling for old argmax mode)

Fixes to llama2 cpu compilation and studio UI, schedulers

---

apps/language_models/scripts/vicuna.py
apps/language_models/src/model_wrappers/vicuna_sharded_model.py
shark/iree_utils/compile_utils.py

- fix dynamic input issue with lmhead layer 
- Disables sharing of device_arrays across shards - unsupported rn.
- Mmap all the shards for faster execution
- fix time calculation for sharded

improved sharded performance and fixed issue with lmhead on rocm

---

apps/language_models/scripts/vicuna.py
apps/language_models/src/model_wrappers/vicuna_sharded_model.py
apps/stable_diffusion/web/ui/stablelm_ui.py

- adds parameters for llama2_70b
- improves performance by chunking layers on a single device to avoid send to host
- changes time displays to display properly on webui
- disables quantization when vmfbs are present

finilized fixes for sharded llama2

---

apps/stable_diffusion/src/models/model_wrappers.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_img2img.py
apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
apps/stable_diffusion/src/utils/__init__.py
apps/stable_diffusion/src/utils/stencils/stencil_utils.py
apps/stable_diffusion/src/utils/utils.py
apps/stable_diffusion/web/ui/img2img_ui.py
apps/stable_diffusion/web/ui/txt2img_sdxl_ui.py
apps/stable_diffusion/web/ui/utils.py

- resizing tweaks so images resized to slider settings
- scheduler list tweaks
- controlnet-specific UI fixes and quality fixes

Many UI fixes and controlnet impovements

---

apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py

We've apparently been doing txt2img with stencils instead of img2img with stencils this entire time.

Fix stencil pipline to use input image

---

apps/shark_studio/api/utils.py

I noticed some duplications in `api/utils.py`
* Remove duplicate os import
* Remove duplicate parse_seed_input function

Studio2: Remove duplications from api/utils.py

---

apps/language_models/scripts/vicuna.py
apps/stable_diffusion/web/ui/stablelm_ui.py
setup_venv.ps1
setup_venv.sh
shark/iree_utils/compile_utils.py

Restricts quantized matmul reassociation flags to cpu compiles of llama2 and pins IREE versions for shark 1.0

 Pin iree versions and fix quant matmul flags.

---

shark/shark_importer.py

New decompose from: https://github.com/pytorch/pytorch/pull/117390
Requied from chatglm model: https://github.com/llvm/torch-mlir/issues/2730

Add decompose of aten._scaled_dot_product_flash_attention_for_cpu

---

requirements.txt

python/turbine_models -> models
shark-turbine -> core

address refactor in turbine

---

requirements.txt

Got iree turbine branch landed so this is good to land now

Update requirements.txt for iree-turbine
